### ISSUE TITLE
Could not enter data using keyboard on iOS Real Device and Simulator (flutter app)

### ISSUE THREAD

**Issue by dlyusko** [appium/appium-flutter-driver#247]
Hello!
In my case I try to enter data into text box using keyboard (not element.sendKeys).
The way I do it is:
1. Click on element (to put focus on that)
2. Call: driver.keys(<myValue>) or driver.sendKeys(<myValue>). (webdriverio)

This approach works ok for emulator and android real device.
But if I try to do it on iOS Real device or simulator -> I can see the following message in appium:
<img width="625" alt="Screenshot 2022-02-14 at 12 13 04" src="https://user-images.githubusercontent.com/84774025/153847243-72899598-3835-4f5a-9460-73e2ac78ccfd.png">

PS: Is there any ways or workarounds to send data via keyboard for webdriverio to have it work for flutter app?

**Comment by KazuCocoa** [comment]
The fact in Appium's keyboard check is by Apple's `exists` API call as: https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Utilities/FBKeyboard.m#L57
API: https://developer.apple.com/documentation/xctest/xcuielement/1500760-exists
Element type: https://developer.apple.com/documentation/xctest/xcuielement/elementtype/keyboard

But Appium tries to interact with the keyboard as https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Commands/FBElementCommands.m#L509

So, based on the result, I guess the keyboard does not exist as iOS/XCTest API.
Flutter team or Apple can fix it, I guess. I wonder vanilla XCTest(UI) also cannot send keys to the keyboard in this case.

**Comment by KazuCocoa** [comment]
This may happen when no keyboad exists. 
https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Utilities/FBKeyboard.m#L53
