### ISSUE TITLE
While switching context from flutter to Native app is working for me(using switchContext("NATIVE_APP")), but getting back to the Flutter context again is not working(using switchContext("FLUTTER")).  getiing webdriver exception.

### ISSUE THREAD

**Issue by dtonge2** [appium/appium-flutter-driver#271]
[HTTP] 
[HTTP] --> GET /wd/hub/session/716f1895-2149-4e5e-b542-5b55dc6b6899/element/eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoiY3VycmVudF90ZW1wX3ZhbHVlIn0/text
[HTTP] {}
[debug] [W3C (716f1895)] Calling AppiumDriver.getText() with args: ["eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoiY3VycmVudF90ZW1wX3ZhbHVlIn0","716f1895-2149-4e5e-b542-5b55dc6b6899"]
[debug] [FlutterDriver] Executing Flutter driver command 'getText'
[debug] [FlutterDriver] >>> {"command":"get_text","finderType":"ByValueKey","keyValueType":"String","keyValueString":"current_temp_value"}
[FlutterDriver] {}
[debug] [W3C (716f1895)] Encountered internal error running command: Error: {}
[debug] [W3C (716f1895)]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:94:35)
[debug] [W3C (716f1895)]     at IsolateSocket.socket.call (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/observatory.ts:66:17)
[debug] [W3C (716f1895)]     at runMicrotasks (<anonymous>)
[debug] [W3C (716f1895)]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[HTTP] <-- GET /wd/hub/session/716f1895-2149-4e5e-b542-5b55dc6b6899/element/eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoiY3VycmVudF90ZW1wX3ZhbHVlIn0/text 500 57 ms - 501
[HTTP] 
[HTTP] --> GET /wd/hub/session/38eaad12-42f8-4f9a-9ae7-7fe1cbd9a7c9/timeouts
[HTTP] {}
[debug] [GENERIC (38eaad12)] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
[debug] [GENERIC (38eaad12)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:243:15)
[debug] [GENERIC (38eaad12)]     at /usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:423:15
[debug] [GENERIC (38eaad12)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [GENERIC (38eaad12)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
[debug] [GENERIC (38eaad12)]     at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
[debug] [GENERIC (38eaad12)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [GENERIC (38eaad12)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:281:22
[debug] [GENERIC (38eaad12)]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:354:14)
[debug] [GENERIC (38eaad12)]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:365:14)
[debug] [GENERIC (38eaad12)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:410:3)
[debug] [GENERIC (38eaad12)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [GENERIC (38eaad12)]     at logger (/usr/local/lib/node_modules/appium/node_modules/morgan/index.js:144:5)
[debug] [GENERIC (38eaad12)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [GENERIC (38eaad12)]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[debug] [GENERIC (38eaad12)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[debug] [GENERIC (38eaad12)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[HTTP] <-- GET /wd/hub/session/38eaad12-42f8-4f9a-9ae7-7fe1cbd9a7c9/timeouts 404 18 ms - 1948
[HTTP] 
[BaseDriver] Shutting down because we waited 60 seconds for a command
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [WD Proxy] Matched '/' to command name 'deleteSession'
[debug] [WD Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:8200/wd/hub/session/db9496ff-db99-45e1-b24b-430d5680a162] with no body
[debug] [WD Proxy] Got response with status 200: {"sessionId":"db9496ff-db99-45e1-b24b-430d5680a162","value":null}
[debug] [ADB] Running '/Users/dhirajtonge/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop com.example.the_weather_channel_poc'
[debug] [UiAutomator2] Capability 'fullReset' set to 'true', Uninstalling 'com.example.the_weather_channel_poc'
[debug] [ADB] Uninstalling com.example.the_weather_channel_poc
[debug] [ADB] Getting install status for com.example.the_weather_channel_poc
[debug] [ADB] Running '/Users/dhirajtonge/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package com.example.the_weather_channel_poc'
[debug] [ADB] 'com.example.the_weather_channel_poc' is installed
[debug] [ADB] Running '/Users/dhirajtonge/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop com.example.the_weather_channel_poc'
[debug] [ADB] Running '/Users/dhirajtonge/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 uninstall com.example.the_weather_channel_poc'
[debug] [Instrumentation] .
[debug] [Instrumentation] Time: 134.614
[debug] [Instrumentation] 
[debug] [Instrumentation] OK (1 test)
[debug] [Instrumentation] The process has exited with code 0
[debug] [ADB] 'adb uninstall com.example.the_weather_channel_poc' command output: Success
[ADB] com.example.the_weather_channel_poc was successfully uninstalled
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200 
[debug] [ADB] Running '/Users/dhirajtonge/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp:8200'
[UiAutomator2] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running '/Users/dhirajtonge/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[HTTP] --> GET /wd/hub/session/38eaad12-42f8-4f9a-9ae7-7fe1cbd9a7c9/timeouts
[HTTP] {}
[debug] [GENERIC (38eaad12)] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
[debug] [GENERIC (38eaad12)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:243:15)
[debug] [GENERIC (38eaad12)]     at /usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:423:15
[debug] [GENERIC (38eaad12)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [GENERIC (38eaad12)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
[debug] [GENERIC (38eaad12)]     at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
[debug] [GENERIC (38eaad12)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [GENERIC (38eaad12)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:281:22
[debug] [GENERIC (38eaad12)]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:354:14)
[debug] [GENERIC (38eaad12)]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:365:14)
[debug] [GENERIC (38eaad12)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:410:3)
[debug] [GENERIC (38eaad12)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [GENERIC (38eaad12)]     at logger (/usr/local/lib/node_modules/appium/node_modules/morgan/index.js:144:5)
[debug] [GENERIC (38eaad12)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [GENERIC (38eaad12)]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[debug] [GENERIC (38eaad12)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[debug] [GENERIC (38eaad12)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[HTTP] <-- GET /wd/hub/session/38eaad12-42f8-4f9a-9ae7-7fe1cbd9a7c9/timeouts 404 3 ms - 1948
[HTTP]

**Comment by KazuCocoa** [comment]
Could you attach the full log as github GIST?
The full log tells us about the environment information etc as well.

**Comment by dhirajtonge** [comment]
https://gist.github.com/dhirajtonge/27639c3969ebad9795243858f6ae0362
