### ISSUE TITLE
Appium error: An unknown server-side error occurred while processing the command. Original error: durationMilliseconds is not a valid options

### ISSUE THREAD

**Issue by rsfgl** [appium/appium-flutter-driver#294]
Im having an issue where I get `Appium error: An unknown server-side error occurred while processing the command. Original error: durationMilliseconds is not a valid options`

This is my code so far, It fails at the wait:for command, Im not sure why could this be because of Appium? Any help would be highly appreciated. Thanks

`driver = await wd.promiseRemote("http://...@hub-cloud.browserstack.com/wd/hub");`

`await driver.init(desiredCaps);`
  
`assert.strictEqual(await driver.execute('flutter:checkHealth'), 'ok');`
`await driver.execute('flutter:clearTimeline');`
`await driver.execute('flutter:forceGC');`
`//Start`
`await driver.execute('flutter:waitFor', find.byValueKey('ExistingAccountLoginFlow'));` //Fails Here
`await driver.elementClick(find.byValueKey('ExistingAccountLoginFlow'));`
`await driver.execute('flutter:waitFor', find.byValueKey('RootCategoryScreen'));`

_Originally posted by @rsfgl in https://github.com/appium-userland/appium-flutter-driver/issues/91#issuecomment-1165099573_

Update this is the command given to appium `["flutter:waitFor","eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoiRXhpc3RpbmdBY2NvdW50TG9naW5GbG93Iiwia2V5VmFsdWVUeXBlIjoiU3RyaW5nIn0","e059f228-2979-403d-b96c-e23746d792a4"]`

**Comment by rsfgl** [comment]
I seem to have fixed it by doing `await driver.execute('flutter:waitFor', [find.byValueKey('ExistingAccountLoginFlow'), 1]);`

**Comment by KazuCocoa** [comment]
Perhaps the key was not necessary
