### ISSUE TITLE
I'm using Appium flutter driver to automate flutter app, we've already automated 2 screen, but once we logged in to the app getting timeout for all the locators on home page not even interacting with any of UI elements using flutter finder

### ISSUE THREAD

**Issue by ommoneynmore** [appium/appium-flutter-driver#305]
Appium version: 1.22.3
Emulator
emulator and real device both
OS: Linux
Any help/input will be appreciated

**Comment by bikashmoneynmore** [comment]
@KazuCocoa  Please help, we are **BLOCKED** from few days

**Comment by bikashmoneynmore** [comment]
@KazuCocoa  This is the log details. The test scenario runs fine up-to log in process after login when user lands on homepage then driver is unable to locate any element.

**Comment by KazuCocoa** [comment]
flutter_driver returned the below error message. This driver itself cannot do anything for this kind of error since it was by https://api.flutter.dev/flutter/flutter_driver/flutter_driver-library.html . The root cause is potentially the view's implementation stuff.


```
[debug] �[35m[MJSONWP (ecc8c68f)]�[39m Calling AppiumDriver.execute() with args: ["flutter:waitFor",[{"ELEMENT":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoicmV3YXJkc1BvaW50In0","element-6066-11e4-a52e-4f735466cecf":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoicmV3YXJkc1BvaW50In0"},20],"ecc8c68f-4913-43fa-8eee-23b3d2e2a830"]
[debug] �[35m[FlutterDriver]�[39m Executing Flutter driver command 'execute'
[debug] �[35m[FlutterDriver]�[39m >>> {"command":"waitFor","finderType":"ByValueKey","keyValueType":"String","keyValueString":"rewardsPoint","timeout":20000}[debug] �[35m[FlutterDriver]�[39m <<< {"isError":true,"response":"Timeout while executing waitFor: TimeoutException after 0:00:20.000000: Future not completed\n","type":"_extensionType","method":"ext.flutter.driver"} | previous command waitFor
[debug] �[35m[MJSONWP (ecc8c68f)]�[39m Encountered internal error running command: Error: Cannot execute command waitFor, server reponse {
[debug] �[35m[MJSONWP (ecc8c68f)]�[39m "isError": true,
[debug] �[35m[MJSONWP (ecc8c68f)]�[39m "response": "Timeout while executing waitFor: TimeoutException after 0:00:20.000000: Future not completed\n",
[debug] �[35m[MJSONWP (ecc8c68f)]�[39m "type": "_extensionType",
[debug] �[35m[MJSONWP (ecc8c68f)]�[39m "method": "ext.flutter.driver"
[debug] �[35m[MJSONWP (ecc8c68f)]�[39m }
[debug] �[35m[MJSONWP (ecc8c68f)]�[39m at FlutterDriver.exports.executeElementCommand (/tmp/.mount_AppiumGQbZ0F/resources/app/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/observatory.ts:133:11)
```

I guess `getRenderTree` command may help to see what kind of elements are available in the view.

**Comment by bikashmoneynmore** [comment]
Thank you so much @KazuCocoa . For providing this much of information and support. We try to explore more about it and once we will solve the issue we will let you know.

**Comment by quyxanh019** [comment]
I have the same problem as above

**Comment by bikashmoneynmore** [comment]
This is some serious problem. Please help in this @KazuCocoa . Unable to figure out the issue

**Comment by KazuCocoa** [comment]
It seems like https://github.com/flutter/flutter/issues/24795 is a similar one. I guess https://github.com/flutter/flutter/issues/36244 as well. Perhaps animation etc blocked the flutter_driver (by Flutter team)'s process.

What I remember is https://github.com/appium-userland/appium-flutter-driver/issues/177#issuecomment-919270651 might help in some cases https://api.flutter.dev/flutter/flutter_driver/SetFrameSync-class.html

This driver itself pass flutter_driver commands to the DartVM and gets the response, so this driver cannot do so much, unfortunately.

**Comment by iamsobowale** [comment]
> Appium version: 1.22.3 Emulator emulator and real device both OS: Linux Any help/input will be appreciated

Were you Able to run the flutter automated test?

**Comment by bikashmoneynmore** [comment]
Yup. Now it's working perfectly

**Comment by bikashmoneynmore** [comment]
@iamsobowale Please try with this one  " driver.execute('flutter:setFrameSync', true , 3500);"

**Comment by iamsobowale** [comment]
> @iamsobowale Please try with this one " driver.execute('flutter:setFrameSync', true , 3500);"

I really have a problem with the whole setup, can I have your email so we can setup a google meeting and show you what I have?

**Comment by bikashmoneynmore** [comment]
Sure @iamsobowale  Please contact on bikashroshan000@gmail.com

**Comment by KazuCocoa** [comment]
Please create a new issue if needed
