### ISSUE TITLE
Publish Kotlin finder via https://jitpack.io/

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium-flutter-driver#341]
As same as appium java client

**Comment by KazuCocoa** [comment]
still wip, but https://github.com/appium-userland/finder-kotlin is for this.

**Comment by jigar-f** [comment]
Any update on this @KazuCocoa, I want to use Flutter-Finder as gradle dependencies any way I can do this?

**Comment by jigar-f** [comment]
ifanyone want to use this as gradle here-:https://github.com/getlantern/finder-kotlin

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-espresso-driver/pull/1021 would help for this

**Comment by KazuCocoa** [comment]
https://jitpack.io/#appium/appium-flutter-driver/main-SNAPSHOT
