### ISSUE TITLE
Dart Observatory URI undefined

### ISSUE THREAD

**Issue by VGVTKH** [appium/appium-flutter-driver#376]
Current Behavior
While running tests at MAC mini (12.6.1 Monterey) for iOS (iPhone SE2 16.1.1) occurs error when trying to run dart observatory:
E selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Failed to connect 30 times. Aborting.
E Stacktrace:
E UnknownError: An unknown server-side error occurred while processing the command. Original error: Failed to connect 30 times. Aborting.
E at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:956:9)
E at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:435:35)

Log from appium:

�[35m[FlutterDriver]�[39m Attempt https://github.com/appium/appium/pull/1
�[35m[FlutterDriver]�[39m Connecting to Dart Observatory: undefined
�[35m[FlutterDriver]�[39m [object Object]
�[35m[FlutterDriver]�[39m Check Dart Observatory URI undefined
�[35m[FlutterDriver]�[39m Waiting 3 seconds before trying...
�[35m[FlutterDriver]�[39m Attempt https://github.com/appium/appium/pull/2
�[35m[FlutterDriver]�[39m Connecting to Dart Observatory: undefined
�[35m[FlutterDriver]�[39m [object Object]
�[35m[FlutterDriver]�[39m Check Dart Observatory URI undefined
�[35m[FlutterDriver]�[39m Waiting 3 seconds before trying...
�[35m[FlutterDriver]�[39m Attempt https://github.com/appium/appium/pull/3
�[35m[FlutterDriver]�[39m Connecting to Dart Observatory: undefined
�[35m[FlutterDriver]�[39m [object Object]
�[35m[FlutterDriver]�[39m Check Dart Observatory URI undefined
�[35m[FlutterDriver]�[39m Waiting 3 seconds before trying...
�[35m[FlutterDriver]�[39m Attempt https://github.com/appium/appium/pull/4
�[35m[FlutterDriver]�[39m Connecting to Dart Observatory: undefined
�[35m[FlutterDriver]�[39m [object Object]
�[35m[FlutterDriver]�[39m Check Dart Observatory URI undefined
�[35m[FlutterDriver]�[39m Waiting 3 seconds before trying...

Flutter app, built in debug mode, all things needed for running it at iOS is done (cert singed, developer team added in cape act)

Script is able to install app, run WebDriverAgent, and then stop at the first app screen
Everything works at android, but not at ios

Expected Behavior
Dart observatory is working

Minimal Reproducible Example
@pytest.fixture(scope='session')
def appium_service():
logger.info('Starting appium service on port: %s.', APPIUM_PORT)
appium_service = AppiumService()
with open(file='logs/appium.log', mode="w", encoding='utf8') as appium_logs:
appium_service.start(
args=['-p', str(APPIUM_PORT), '--base-path', '/wd/hub'],
stdout=appium_logs,
stderr=subprocess.STDOUT
)
yield
logger.info('Stopping appium service.')
appium_service.stop()

@pytest.fixture(scope='function')
def appium_driver_function(remote_run, appium_service):
phone_udid = LOCAL_PHONE_ADDRESS
url = f'[http://127.0.0.1:{APPIUM_PORT}/wd/hub](http://127.0.0.1:%7BAPPIUM_PORT%7D/wd/hub)'
logger.info('Starting webdriver')
stf_capabilities = {
'udid': f'{phone_udid}',
'platformName': 'iOS',
"platformVersion": "16.1.1",
'appium:automationName': 'Flutter',
'appium:autoAcceptAlerts': True,
'appium:autoGrantPermissions': True,
'xcodeOrgId': 'ID',
'noReset': True,
'xcodeSigningId': 'iPhone Developer',
'app': APP_PATH,
'appium:bundleId': "bundle.id",
'appium:appPackage': APP_NAME,
'appium:appActivity': '.MainActivity',
'appium:clearSystemFiles': True
}
logger.info(url)
driver = webdriver.Remote(url, stf_capabilities)
yield driver
driver.quit()
logger.info('Stopping webdriver')

Environment
Operating system: MAC mini (12.6.1 Monterey)
If running via appium CLI...
Appium CLI version (output of appium --version): 2.0.0-beta.46
Node.js version (output of node --version): v16.0.0
npm version (output of npm --version): 8.19.2
Last appium version which did not exhibit the problem: X
If running Appium Desktop, its version: X
Appium driver(s) and their version(s): flutter@1.11.0
Appium plugin(s) and their version(s): X
Platform and version under test: X
Real device or emulator/simulator: iOS (iPhone SE2 16.1.1)
-App in flutter (3.0+)

**Comment by KazuCocoa** [comment]
Did you try out `profile` build? I wonder if it is related to https://github.com/appium-userland/appium-flutter-driver/issues/115

**Comment by VGVTKH** [comment]
> Did you try out `profile` build? I wonder if it is related to #115

Seems like not related, because tests are able to run home screen from app, and then they are waiting for dart observatory, so app is running correctly

**Comment by KazuCocoa** [comment]
then, could you share the full device log and the appium server log as GitHub GIST to check the observatory URL in the device log?
Afaik, only the profile build prints the observatory URL in the system log for iOS

**Comment by thetanz-geoff** [comment]
Was also seeing this issue when using Flutter latest (`beta` channel, `3.7.0-1.1.pre`; used `--profile` to build then `xcodebuild -exportArchive` to generate `.ipa` from the `.xcarchive`).

I think I'd been a little less than patient while waiting for the test to run, and had fiddled with the device, starting my app. Note that the default behaviour shown in the example (`"appium:noReset": true`) will *not* forcibly quit and reinstall the app.

The Dart Observatory URL is output to the device logs only when an app is started. So having already started my app, my experience was that I would see the "Automation Running" overlay, but "Connecting to Dart Observatory: undefined" would sit and spin for 30 attempts at 3s each, then retry a bunch of times, continuing to fail because my app was already loaded.

I found during that time if I quit my app, then after that 90s timeout the app will be restarted and the driver is able to pick up the Dart Observatory URL on the new run, then connects fine and runs the script.

As a long-term fix, I'll now manually restart my app every time, or set the `appium:noReset` capability to `false` so that the app is closed, uninstalled, reinstalled and run from scratch.

Hope this helps you @VGVTKH.

**Comment by denysord88** [comment]
Hi all.
I'm checking if it's possible to automate UI testing with appium-flutter-driver in Bitrise CI.
I successfully build in Bitrise a simplest Flutter application and started it on the iOS simulator,
but appium-flutter-driver can't connect to the Dart VM to start interaction with my Flutter app.

Could you please give some advise how to check the Dart VM state or get this Dart Observatory URI using Bash script or maybe Bitrise step?

**Here is the Appium output that proofs application was started on the Simulator:**
[Xcode]     t =     0.89s Open com.denysord1988.pocapp
[Xcode]
[Xcode]     t =     0.89s     Launch com.denysord1988.pocapp
[Xcode]
[Xcode]     t =     0.95s         Setting up automation session
[Xcode]
[Xcode] 2023-01-04 14:35:36.879807+0000 WebDriverAgentRunner-Runner[8929:39430] Waiting up to 10s until com.denysord1988.pocapp is in idle state (including animations)
[Xcode]     t =     1.66s         Wait for com.denysord1988.pocapp to idle
[Xcode]
[Xcode] 2023-01-04 14:35:38.389383+0000 WebDriverAgentRunner-Runner[8929:39430] Getting the most recent active application (out of 1 total items)
[Xcode]
[Xcode]     t =     3.17s Find the Application 'com.denysord1988.pocapp'
[Xcode]
[Xcode]     t =     3.18s     Requesting snapshot of accessibility hierarchy for app with pid 8941
[Xcode]
[debug] [XCUITestDriver@983b (68b530d8)] Got response with status 200: {"value":{"sessionId":"61BD7999-D329-4160-999F-80759C706B70","capabilities":{"device":"iphone","browserName":"Pocapp","sdkVersion":"16.1","CFBundleIdentifier":"com.denysord1988.pocapp"}},"sessionId":"61BD7999-D329-4160-999F-80759C706B70"}

**And the next steps for Appium is to connect to a Dart Observatory:**
[FlutterDriver] Attempt #1
[FlutterDriver] Connecting to Dart Observatory: undefined
[FlutterDriver] [object Object]
[FlutterDriver] Check Dart Observatory URI undefined
[FlutterDriver] Waiting 3 seconds before trying...
...
[FlutterDriver] Attempt #29
[FlutterDriver] Connecting to Dart Observatory: undefined
[FlutterDriver] [object Object]
[FlutterDriver] Check Dart Observatory URI undefined
[FlutterDriver] Failed to connect 30 times. Aborting.
[debug] [FlutterDriver] Deleting Flutter Driver session
[debug] [AppiumDriver@23eb] Event 'newSessionStarted' logged at 1672843022550 (14:37:02 GMT+0000 (Greenwich Mean Time))
[debug] [AppiumDriver@23eb] Encountered internal error running command: Error: Failed to connect 30 times. Aborting.

My capabilities:
{
app: ../build/ios/iphonesimulato...,
appium:noReset: false,
autoAcceptAlerts: false,
autoDismissAlerts: false,
automationName: Flutter,
bundleId: com.denysord1988.pocapp,
deviceName: iPhone 13 Pro Max,
enablePerformanceLogging: true,
iosInstallPause: 20000,
newCommandTimeout: 60000,
platformName: IOS,
platformVersion: 16.1,
showIOSLog: true,
showXcodeLog: true,
usePrebuiltWDA: false,
wdaConnectionTimeout: 30000,
wdaLaunchTimeout: 30000,
wdaLocalPort: 4000,
webkitResponseTimeout: 60000
}

Flutter app build using command:
flutter "build" "ios" "--simulator" "--debug" "--no-codesign"

flutter --version
Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 135454af32 (3 weeks ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0
+ flutter devices
2 connected devices:
iPhone 13 Pro Max (mobile) • BB2E3A31-EEF4-4FC4-9A30-7AA1ABD70DBC • ios        • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
macOS (desktop)            • macos                                • darwin-x64 • macOS 12.5.1 21G83 darwin-x64

appium -v
2.0.0-beta.46

java -version
openjdk version "11.0.11" 2021-04-20

mvn -v
Apache Maven 3.8.6

+ appium driver install --source=npm appium-flutter-driver
- Installing 'appium-flutter-driver'
✔ Installing 'appium-flutter-driver'
ℹ Driver flutter@1.11.0 successfully installed
- automationName: Flutter
- platformNames: ["iOS","Android"]
+ appium driver list --installed
- Listing installed drivers
✔ Listing installed drivers
- flutter@1.11.0 [installed (NPM)]

**Comment by KazuCocoa** [comment]
What about the profile build?

**Comment by denysord88** [comment]
Profile build works only for real devices but I'm trying to run it on Simulator. It works fine locally but fails in Bitrise

**Comment by KazuCocoa** [comment]
Not sure what Bitrise customizes their environment, but maybe something is it Bitrise specific stuff?

The observatory logic tries to find a websocket URL to the Dart VM by reading the device log. If their environment customized logging stuff, potentially, this does not work.

**Comment by denysord88** [comment]
Thanks, I will try to grab the Simulator logs to check if there is any info related to the Dart VM

**Comment by KazuCocoa** [comment]
Logs for simulators are available via `log` like getting logs from the host machine.
https://github.com/appium/appium-xcuitest-driver/blob/166d4e3425c92b041f835df988a071e55a0f2862/lib/device-log/ios-simulator-log.js#L28 is what Appium/XCUITest driver checks the log. Appium flutter driver relies on the method

**Comment by denysord88** [comment]
Update:
I added command to get a Simulator logs before my tests but it doesn't work in Bitrise "Script" step.
`nohup xcrun simctl spawn booted log stream --style compact --level debug | tee > $BITRISE_DEPLOY_DIR/output.log >/dev/null 2>&1 &`
...
**Error from getpwuid_r: 25 (Inappropriate ioctl for device)**

But it's working fine locally. Trying to solve this "Inappropriate ioctl" issue..

**Comment by KazuCocoa** [comment]
thanks for the update. Then... I guess Bitrise has a limit to conduct commands on their env. Their customer support will be necessary I assume.

**Comment by KazuCocoa** [comment]
Hm, the log format itself should be matched with https://github.com/appium-userland/appium-flutter-driver/blob/d0e70b161b4d9a2ae261d972a6bc92156833d23b/driver/lib/sessions/observatory.ts#L188
Then, one possible thing is the timing to get logs.

Current logic expects:
1. start log capture
2. launch the app under test
3. parse logs to get the url

but on their env, the 2) could begin before 1)'s log capture starts for some reason. I wonder slow environment affects it, or something

**Comment by denysord88** [comment]
But I'm launching the application (2) and starting logs capturing (1) by Appium in the same test framework. How this steps can be misplaced? Is there any timeout in driver capabilities to wait launching the app before logs capturing will be started?

**Comment by KazuCocoa** [comment]
I haven't tested, but I wonder if starting a session without app/packageName, and starting the app under test via `driver.activateApp(appId)` later work.

Potentially we need to update this driver code to allow the scenario though..

**Comment by denysord88** [comment]
I will try to test it, thanks for the idea.

**Comment by KazuCocoa** [comment]
Maybe https://github.com/appium-userland/appium-flutter-driver/pull/395 needs to achieve https://github.com/appium-userland/appium-flutter-driver/issues/376#issuecomment-1379354950

**Comment by KazuCocoa** [comment]
v1.12.0 can start without any `app` nor `appPackage`/`bundleId`. Then, you can install the app via `installApp` and activate it in the flutter context. It may help to check something in the Bitrise environment

**Comment by denysord88** [comment]
Great thanks! I will try to replace my current version with this one and check

**Comment by denysord88** [comment]
Update

I changed the code to start the app later:
```
System.out.println("!!! 5");
Thread.sleep(120000);
driver.installApp(IOS_APP_PATH);
System.out.println("!!! 6");
Thread.sleep(120000);
driver.activateApp("com.denysord1988.pocapp");
System.out.println("!!! 7");
Thread.sleep(60000);
driver.executeScript("flutter:waitForFirstFrame");
System.out.println("!!! 8");
FlutterFinder finder = new FlutterFinder(driver);
finder.byText("Check access").click();
assertEquals(finder.byValueKey("_accessHeaderTitle").getText(), "Access");
...
```
In the iOS Simulator logs:
`2023-01-18 17:32:29.313 Df Runner[8957:a57e] (Flutter) flutter: The Dart VM service is listening on http://127.0.0.1:49859/ccUkJw5YQvs=/`

But in test framework logs still undefined:
```
...
!!! 5
[HTTP] --> POST /wd/hub/session/fd846237-7816-4975-81bf-6306f3042263/appium/device/install_app
[HTTP] {"appPath":"/Users/vagrant/git/build/ios/iphonesimulator/Runner.app"}
[debug] [FlutterDriver@bc73 (fd846237)] Calling AppiumDriver.installApp() with args: ["/Users/vagrant/git/build/ios/iphonesimulator/Runner.app",null,null,null,"fd846237-7816-4975-81bf-6306f3042263"]
[debug] [FlutterDriver] Executing Flutter driver command 'installApp'
[debug] [FlutterDriver@bc73 (fd846237)] Responding to client with driver.installApp() result: null
[HTTP] <-- POST /wd/hub/session/fd846237-7816-4975-81bf-6306f3042263/appium/device/install_app 200 6 ms - 14
[HTTP] 
[BaseDriver] Using local app '/Users/vagrant/git/build/ios/iphonesimulator/Runner.app'
[XCUITestDriver@5551 (f1cceeb9)] Installing '/Users/vagrant/git/build/ios/iphonesimulator/Runner.app' to the Simulator with UDID 'BDE81691-7008-4B16-8189-C187F8D1030C'
!!! 6
[XCUITestDriver@5551 (f1cceeb9)] Installation of '/Users/vagrant/git/build/ios/iphonesimulator/Runner.app' succeeded
[HTTP] --> POST /wd/hub/session/fd846237-7816-4975-81bf-6306f3042263/appium/device/activate_app
[HTTP] {"bundleId":"com.denysord1988.pocapp"}
[debug] [FlutterDriver@bc73 (fd846237)] Calling AppiumDriver.activateApp() with args: ["com.denysord1988.pocapp",null,null,null,"fd846237-7816-4975-81bf-6306f3042263"]
[debug] [FlutterDriver] Executing Flutter driver command 'activateApp'
[debug] [XCUITestDriver@5551 (f1cceeb9)] Proxying [POST /wda/apps/launch] to [POST http://127.0.0.1:4000/session/BF0DCF1D-3109-4095-AE53-0586254FB169/wda/apps/launch] with body: {"bundleId":"com.denysord1988.pocapp"}
[FlutterDriver] Attempt #1
[FlutterDriver] Connecting to Dart Observatory: undefined
[FlutterDriver] {}
[FlutterDriver] Check Dart Observatory URI no URI found in the device log
[FlutterDriver] Waiting 3 seconds before trying...
[Xcode]     t =   250.70s Open com.denysord1988.pocapp
[Xcode]     t =   250.70s     Launch com.denysord1988.pocapp
[Xcode] 
[Xcode]     t =   250.84s         Setting up automation session
[Xcode] 
[Xcode] 2023-01-18 17:32:28.516870+0000 WebDriverAgentRunner-Runner[8261:38852] Quiescence checks are disabled for com.denysord1988.pocapp application. Making it to believe it is idling
[Xcode] 
[debug] [XCUITestDriver@5551 (f1cceeb9)] Got response with status 200: {"value":null,"sessionId":"BF0DCF1D-3109-4095-AE53-0586254FB169"}
[FlutterDriver] Attempt #2
[FlutterDriver] Connecting to Dart Observatory: undefined
[FlutterDriver] {}
[FlutterDriver] Check Dart Observatory URI no URI found in the device log
[FlutterDriver] Waiting 3 seconds before trying...
[FlutterDriver] Attempt #3
[FlutterDriver] Connecting to Dart Observatory: undefined
[FlutterDriver] {}
...
```

**Comment by denysord88** [comment]
looks like I need some timeout inside
`driver.activateApp("com.denysord1988.pocapp");`
I found another constructor
`default void activateApp(String bundleId, @Nullable BaseActivateApplicationOptions options)`
Is there any examples of that "BaseActivateApplicationOptions" field?

**Comment by lengochoangminh** [comment]
Hello @KazuCocoa and @denysord88, do you guys have the solution for this issue yet?

I had the same issue: "failed to connect to Dart Observatory" when trying with Appium-flutter-driver. The details are below
- https://gist.github.com/lienngo1985/2045d8468c2f72ff77897e8a888d1eff
- Flutter 3.7.7
- Appium 2.0.0-beta.57

Do you have any advice, please?

**Comment by denysord88** [comment]
Hello @lengochoangminh, could you please share the flutter app code? If it's just your example for debug.. I will try to reproduce locally. And please describe the env where you running the test, locally or somewhere in CI?

I'm temporary stopped investigating this issue in Bitrise CI because it's working fine locally on my MacOS laptop. So I will come back to CI issue on the next week.

**Comment by lengochoangminh** [comment]
Hello @denysord88,

Thank you very much for replying to me. Here is my flutter repo https://github.com/lengochoangminh/flutter_fitness.

FYI. I just ran the test locally for researching.

**Comment by denysord88** [comment]
Update: I finished setup the Bitrise pipeline to run Java tests with appium-flutter-driver on iOS simulator. Working fine, the issue with "Dart Observatory URI undefined" error is not reproducing anymore.
