### ISSUE TITLE
enableFlutterDriverExtension() in main.dart stops keyboard, if i remove it appium-flutter-driver is showing handshaking issue

### ISSUE THREAD

**Issue by GarimaVats** [appium/appium-flutter-driver#40]

**Comment by shibupanda** [comment]
@GarimaVats 
EnableFlutterDriverExtention is mandatory for the automation.
Please reach the dev team it may be due to dart version compatibility issue.

**Comment by lsuhov** [comment]
Can you give an example of working versions?

**Comment by truongsinh** [comment]
v1.12.13+hotfix.7 or v1.9.1+hotfix.6 should both work. If it's not working for you, can you report the device and OS you are using?

**Comment by shibupanda** [comment]
@truongsinh it seems it's already reported in flutter community nothing to do in Appium flutter driver. I have tried with latest dart and flutter version.
https://github.com/flutter/flutter/issues/15415

**Comment by GarimaVats** [comment]
@truongsinh I tried almost all appium enter key function. I was using appium 1.16.0. I used it for both android and iOS devices and both OS Mac and windows.

**Comment by truongsinh** [comment]
> @truongsinh I tried almost all appium enter key function. I was using appium 1.16.0. I used it for both android and iOS devices and both OS Mac and windows.

From https://github.com/flutter/flutter/issues/15415#issuecomment-581532972, looks like @jonahwilliams meant we have to have the solution ourselves. @GarimaVats can you describe the reason you need to interact with on-screen keyboard?

**Comment by ahashmi24** [comment]
@truongsinh 
it blocks us to use sendKeys() function on android/iOS native.

There must be a scenario where we have to use sendKeys() to handle any native element in android or iOS (e.g XCUIElementTypePickerWheel)

**Comment by truongsinh** [comment]
So let me see if I understand you correctly, here's the reproducing step:

1. open app
2. switch to Flutter context
3. select text box
4. send some keystrokes
5. switch to native context
6. send some keystrokes

It is at the 6th step that you are blocked?

**Comment by ahashmi24** [comment]
@truongsinh 
Yes, it is throwing an exception on 6th step.

**Comment by shibupanda** [comment]
@truongsinh looks like @jonahwilliams added caveats for this.
https://github.com/flutter/flutter/pull/50017. 
Whether we need to add it in our README file as well.

**Comment by dvyAb** [comment]
@truongsinh  
Hello,

Do you have any news please?

**Comment by yahyakara** [comment]
Do you have any news please? ?

**Comment by anu-09-stack** [comment]
Respected @shibupanda any update for the enableFlutterDriverExtension() in main.dart and stops keyboard and unable to enter any text into textfield

**Comment by SushmaVB2512** [comment]
has anyone found a solutions to this issue yet?

**Comment by mustafahawari** [comment]
has anyone found a solution for this yet?

**Comment by kritika333** [comment]
Any solution on this ?

**Comment by KazuCocoa** [comment]
The keyboard itself does not appear as the flutter_driver lib behavior.
So far, sending keys via uia2/xcuitest native context could be a workaround as this driver https://github.com/appium/appium-flutter-driver/issues/607#issuecomment-1774184865
