### ISSUE TITLE
How to install the Flutter app with extra options?

### ISSUE THREAD

**Issue by okaruk** [appium/appium-flutter-driver#415]
Hey, there!

I see `appium-flutter-driver v1.12.0` supports installing the app using `installApp`, which accepts the absolute path to `.apk` file and some `options` list: `installApp(appPath, options)`.

Could you provide the list of supported `options` and an example of how to pass them to `installApp` method?

`UPDATE:`
This command written on Ruby installs the app, but I wish to pass some `options` here:
`@driver.install_app(/path/to/app.apk)`

**Comment by KazuCocoa** [comment]
Do you mean https://www.rubydoc.info/gems/appium_lib_core/Appium/Core/Base/Driver#install_app-instance_method ?

Or https://appium.github.io/appium-xcuitest-driver/4.16/execute-methods/#mobile-installapp also could do.
