### ISSUE TITLE
Question: Create a list of all Elements and their Valuekeys

### ISSUE THREAD

**Issue by FotogyDS** [appium/appium-flutter-driver#428]
I am currently facing the problem that i can't find a way to create a list of all elements and their Valuekeys, of a apk. Is there anyway that can be resolved? Using the `driver.find_elements(by=AppiumBy.CLASS_NAME,value='android.widget')` leaves me with an Error message. So there has to be a way to do it with the Finder.

Any help would be appreciated!

**Comment by thuonglai** [comment]
You can switch to NATIVE_APP to using selector of Android element

**Comment by FotogyDS** [comment]
Sorry, i think i can't quite follow, where can i switch to NATIVE_APP?

**Comment by KazuCocoa** [comment]
https://github.com/appium/python-client/blob/d5b84b899e4abad6afd914d0e5342476cb955de2/appium/webdriver/switch_to.py#L38 should help for the switching context.
