### ISSUE TITLE
Question: Is is possible to connect to existing observatory_url with 'appium:observatoryWsUri' capability?

### ISSUE THREAD

**Issue by Ernst-D** [appium/appium-flutter-driver#429]
Hey!

So, I wonder if it possible to do the next trick:

I run the app in debug mode via flutter run -> I know what observatoryWsUri from previous command -> I start appium session with noReset: true, automationName: "Flutter" and "appium:observatoryWsUri":"ws://0.0.0.0:1224/etc/ws" and then sending appium command to my application, which in a debug mode from flutter_cli

Is it possible? Since, it would be pretty convenient to have full control, running flutter app with plugged devtools, and meanwhile execution appium tests

Thanks!

**Comment by denysord88** [comment]
Hi @Ernst-D , I'm facing the issue with getting observatoryWsUri by Appium automatically in CI. So your idea with starting Appium framework and providing "appium:observatoryWsUri" capability can solve my issue too.
You can check this thread https://github.com/appium-userland/appium-flutter-driver/issues/376 to start Appium without starting the application. Maybe start framework with "appium:observatoryWsUri" capability and without bundle id can help in your case.

"I know what observatoryWsUri from previous command" could you please share the way how you are getting this observatoryWsUri after flutter run command?

**Comment by Ernst-D** [comment]
Hey @denysord88 , thank you for response, I'll definitely try this

I have to get it manually (which is okay I guess, since I want to test specific flutter app, which sits on specific URL): 

![image](https://user-images.githubusercontent.com/80358262/226274652-f4b7ff14-6ca0-45b3-9cf7-20d6bef7dd5c.png)

1. Execute `flutter run`  in debug mode
2. We see all urls available to us (devtools, observatory and etc)
3. Copy url from console log and paste that to capabilities
![image](https://user-images.githubusercontent.com/80358262/226275082-e7adef31-8e30-4e9f-9105-53d5d951db88.png)

**Comment by denysord88** [comment]
Hi @Ernst-D, here is my example, you can browse thru the repo to see the other code https://github.com/denysord88/pocapp/blob/main/TA_Appium_POCAPP/src/main/java/tests/MyFirstTest.java
I will try to add there your logic of getting the observatoryWsUri and set it as capability before starting the Appium driver instead of starting the app programmatically by Appium.
I will update you later today if it will works for me.
