### ISSUE TITLE
Application is launch failed and valuekey couldn't click. 

### ISSUE THREAD

**Issue by Girisankar1** [appium/appium-flutter-driver#453]
Hi,
I am having problems with the application launch and the flutter value key couldn't click the flutter app.
the flutter_driver is deprecated so, I couldn't add the enableFlutterDriverExtension method so, so the build application is not accessible to appium-flutter-driver and appium-flutter-finder. Any update to using the integration test package in appium-flutter-driver?

Build application thrown below exception in terminal:
![image](https://user-images.githubusercontent.com/97234211/234778392-5fd48114-d2bd-4b0a-bc65-53e593968fc9.png)

**Comment by KazuCocoa** [comment]
close as the latest version has some improvements to find an observatory url. Lets try the latest one first
