### ISSUE TITLE
TextField does not clear for elementClear method call.

### ISSUE THREAD

**Issue by Sagarz2422** [appium/appium-flutter-driver#459]
Hello there team,
I am currently working on the e2e testing with appium for one of the projects. But usecase is i want to clear the field and enter the new data.
But in some case its not clearing it.
Below is the code that i did try:
```
 await this.driver.elementClear("object name to clear");
```
```
descendant({of: byValueKey('capture_amount_field'),matching: byType('TextField'),firstMatchOnly: true });
```
Just an FYI its adding the amount for first time that means its able to find the widget. But it cannot clear it.
Let me know if any one has faced this kind of issues. Or any alternative
Thanks

**Comment by KazuCocoa** [comment]
It sets an empty string behind the command.
https://github.com/appium/appium-flutter-driver/blob/bbb72043a08a7f22e245e44f5637c4bfb7024de2/driver/lib/commands/element.ts#L22-L24
Possibly the Flutter API was not able to enter an empty string https://github.com/appium/appium-flutter-driver/blob/bbb72043a08a7f22e245e44f5637c4bfb7024de2/driver/lib/commands/execute.ts#L177C55-L177C65

An alternative method is doing it via the NATIVE_APP context, afaik.
