### ISSUE TITLE
Cannot use the "automationName" = "flutter" as a property 

### ISSUE THREAD

**Issue by Nowshin23** [appium/appium-flutter-driver#512]
hi, I am using Appium 2.0. And I cannot use "automationName = flutter". Appium log is given below. 

![image](https://github.com/appium-userland/appium-flutter-driver/assets/133006781/1020d290-464d-4a56-8a7e-606632fee309)

Could anyone please tell where i am doing it wrong? this is my code snippet of capabilities.
![image](https://github.com/appium-userland/appium-flutter-driver/assets/133006781/a1481a24-51e9-439b-ab3d-6b73280ac236)

**Comment by KazuCocoa** [comment]
Could you try out the latest appium flutter driver version with Appium 2.0?
https://github.com/appium-userland/appium-flutter-driver/blob/main/README.md

**Comment by Nowshin23** [comment]
yes i am using appium 2.0 beta 71

**Comment by Nowshin23** [comment]
![image](https://github.com/appium-userland/appium-flutter-driver/assets/133006781/6a4f8715-22fb-4e17-ba44-197b2d0eb3be)
 using this version of flutter driver already

**Comment by KazuCocoa** [comment]
Hm, but your attached one used Appium 1.22.0.

```
[info] [35m[Appium][39m Welcome to Appium v1.22.0
[info] [35m[Appium][39m Non-default server args:
[info] [35m[Appium][39m   allowCors: true
[info] [35m[Appium][39m   address: localhost
[info] [35m[Appium][39m   relaxedSecurityEnabled: true
[info] [35m[Appium][39m   allowInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m   denyInsecure: {
[info] [35m[Appium][39m   }
```

Maybe did you run wrong appium binary?

**Comment by Nowshin23** [comment]
i think this is the appium app version. 
![image](https://github.com/appium-userland/appium-flutter-driver/assets/133006781/3e851b6c-d9f8-4b71-ac61-f090749d76ac)

**Comment by KazuCocoa** [comment]
Then, could you attach the proper appium server log? Also, please try out the latest appium 2 and driver version

**Comment by Nowshin23** [comment]
Hey! closing the issue. i was able to find the issue. I was using Appium Desktop which uses Appium Version 1.22. Now I run the server from the command line and it works perfectly. Thanks for your help!
