### ISSUE TITLE
How appium flutter driver perform open notifications?

### ISSUE THREAD

**Issue by mazis0** [appium/appium-flutter-driver#513]
Hello everyone i have issue with appium flutter driver how to perform open notification on appium flutter driver? Thanks for any help

**Comment by KazuCocoa** [comment]
NATIVE_APP context may help for it

**Comment by mazis0** [comment]
@KazuCocoa thanks for help, but i've another question. how i can switch from flutter to UiAutomator2 for interact with xpath locator. thanks

**Comment by KazuCocoa** [comment]
Did you try out NATIVE_APP context? (of for the contexn api itself?) 

https://github.com/appium-userland/appium-flutter-driver#example
```
  if (process.env.APPIUM_OS === 'android') {
    await driver.switchContext('NATIVE_APP');
    await (await driver.$('~fab')).click();
    await driver.switchContext('FLUTTER');
  } else {
    console.log('Switching context to `NATIVE_APP` is currently only applicable to Android demo app.')
  }
```

https://appium.io/docs/en/2.0/guides/context/
