### ISSUE TITLE
Uninstall Appium-Flutter-Driver

### ISSUE THREAD

**Issue by mazis0** [appium/appium-flutter-driver#545]
Hello i've issue with uninstall appium-flutter-driver, what command for uninstall appium-flutter-driver on terminal? and what command for update version appium-flutter-driver.

Thanks

**Comment by denysord88** [comment]
For me in MacOS Terminal it's
```
sudo rm -rf /Users/username/.appium/node_modules/appium-flutter-driver
appium driver uninstall flutter
appium driver list --installed
sudo appium driver install --source=npm appium-flutter-driver@1.19.1
appium driver list --installed
```

**Comment by denysord88** [comment]
It's not working without sudo in my case, but it's always better to try to run the commands without sudo first. And add sudo only if you don't have enough access.

**Comment by KazuCocoa** [comment]
sudo may be needed if your `node` is sudo privilege. I'd recommend you to prepare non-root user nodejs env like `nvm`, `nodebrew` etc that helps to keep node env in the user local env.

**Comment by mazis0** [comment]
> It's not working without sudo in my case, but it's always better to try to run the commands without sudo first. And add sudo only if you don't have enough access.

thank you, solved
