### ISSUE TITLE
Flutter Driver Terminates Appium Server After Test Completion

### ISSUE THREAD

**Issue by baselalali** [appium/appium-flutter-driver#569]
Dear Appium Community,

I hope this message finds you well. I am writing to report an issue I've encountered while using Appium in conjunction with Flutter Driver for mobile app testing. The problem involves the Appium server being terminated by the Flutter Driver when the test is completed.

Here are the details of the issue:

Appium Version and Driver Versions:

```
**Appium Version: 2.0.1 (REV 9600617c52d0d2e48493424c529ac6c945d2775b)
Loaded Drivers: xcuitest@4.35.0, uiautomator2@2.29.8, flutter@1.22.0
Loaded Plugins: images@2.1.2**
```
Issue Description:

When running tests using Flutter Driver in conjunction with Appium, the Appium server gets unexpectedly terminated at the end of the test execution. This behavior occurs even though the test completes successfully, leading to disruption in the automation workflow.

Logs:

Below is a snippet of the relevant logs that illustrate the sequence of events:

log
```
**[debug] [FlutterDriver@a5cf (68cd7f96)] Calling AppiumDriver.deleteSession() with args: ["68cd7f96-62c1-4a05-85eb-36367bbbde0c"]
[debug] [AppiumDriver@40a6] Event 'quitSessionRequested' logged at 1694791885221 (17:31:25 GMT+0200)
[AppiumDriver@40a6] Removing session 68cd7f96-62c1-4a05-85eb-36367bbbde0c from our master session list
[debug] [FlutterDriver@a5cf (68cd7f96)] Deleting Flutter Driver session
...
[debug] [AppiumDriver@40a6] Event 'quitSessionFinished' logged at 1694791885495 (17:31:25 GMT+0200)
[debug] [AppiumDriver@40a6] Received response: null
[debug] [AppiumDriver@40a6] But deleting session, so not returning
[debug] [AppiumDriver@40a6] Responding to client with driver.deleteSession() result: null**
```
Expected Behavior:

The expected behavior is that the Appium server should remain active and available to handle additional automation tasks even after the test execution is completed.

Additional Information:

This issue occurs consistently in my test environment.
The test cases are executed successfully using Flutter Driver, but the termination of the Appium server disrupts the overall automation workflow.
Request for Assistance:

I kindly request assistance from the Appium community in diagnosing and resolving this issue. Any insights, guidance, or solutions would be greatly appreciated. If additional information or logs are needed, please let me know, and I will provide them promptly.

Thank you for your time and support.

Best regards,

**Comment by KazuCocoa** [comment]
Please attache the full appium server log

**Comment by baselalali** [comment]
Follow the link

https://gist.github.com/baselalali/f17fd8c4661d0514e8a6375bc9e19d0e

**Comment by KazuCocoa** [comment]
> the Appium server gets unexpectedly terminated at the end of the test execution.

What do you mean...?

```
[HTTP] --> DELETE /session/77896cc9-fade-457c-a463-932ea6139ef6
[HTTP] {}
[debug] [FlutterDriver@f919 (77896cc9)] Calling AppiumDriver.deleteSession() with args: ["77896cc9-fade-457c-a463-932ea6139ef6"]
[debug] [AppiumDriver@f824] Clearing new command timeout pre-emptively since plugin(s) will handle this command
[AppiumDriver@f824] Plugins which can handle cmd 'deleteSession': images
[AppiumDriver@f824] Plugin images is now handling cmd 'deleteSession'
[AppiumDriver@f824] Executing default handling behavior for command 'deleteSession'
[debug] [AppiumDriver@f824] Event 'quitSessionRequested' logged at 1695108487333 (09:28:07 GMT+0200 (Mitteleuropäische Sommerzeit))
[AppiumDriver@f824] Removing session 77896cc9-fade-457c-a463-932ea6139ef6 from our master session list
[debug] [FlutterDriver@f919 (77896cc9)] Deleting Flutter Driver session
[debug] [AndroidUiautomator2Driver@f383 (e78bf917)] Deleting UiAutomator2 session
[debug] [AndroidUiautomator2Driver@f383 (e78bf917)] Deleting UiAutomator2 server session
[debug] [AndroidUiautomator2Driver@f383 (e78bf917)] Matched '/' to command name 'deleteSession'
[debug] [AndroidUiautomator2Driver@f383 (e78bf917)] Proxying [DELETE /] to [DELETE http://127.0.0.1:8200/session/ac29c10a-bd9c-4e9e-a5ff-dcbdb3503ad3] with no body
[debug] [AndroidUiautomator2Driver@f383 (e78bf917)] Got response with status 200: {"sessionId":"ac29c10a-bd9c-4e9e-a5ff-dcbdb3503ad3","value":null}
[debug] [ADB] Running '/Users/baselalali/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5555 shell dumpsys activity services io.appium.settings/.recorder.RecorderService'
[debug] [ADB] Running '/Users/baselalali/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5555 shell am force-stop de.dfb.eventapp.refz.debug'
[FlutterDriver] Connection to ws://127.0.0.1:44323/8rcunDj8XCY=/ws closed
[FlutterDriver] Connection to ws://127.0.0.1:44323/8rcunDj8XCY=/ws closed
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200 
[debug] [ADB] Running '/Users/baselalali/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5555 forward --remove tcp:8200'
[AndroidUiautomator2Driver@f383 (e78bf917)] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running '/Users/baselalali/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5555 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[debug] [AppiumDriver@f824] Event 'quitSessionFinished' logged at 1695108487625 (09:28:07 GMT+0200 (Mitteleuropäische Sommerzeit))
[debug] [AppiumDriver@f824] Received response: null
[debug] [AppiumDriver@f824] But deleting session, so not returning
[debug] [AppiumDriver@f824] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /session/77896cc9-fade-457c-a463-932ea6139ef6 200 295 ms - 14
```

After calling delete request as above, your appium server process stopped?


Usually, Appium prints like below hook log when it gets a signal, but your log did not.
```
[Appium] Received SIGINT - shutting down
```

Thus, do you mean the appium server crashed unexpectedly?

**Comment by baselalali** [comment]
I mean that the Appium server is stopped after finishing the execution. All AfterHooks are executed for this session.

`Usually, Appium prints a hook log like the one below when it receives a signal, but your log did not.
`
`So, do you mean the Appium server crashed unexpectedly?
`
 I don't think the Appium server crashed. It was stopped by the execution o`f [HTTP] --> DELETE /session/77896cc9-fade-457c-a463-932ea6139ef6`. Who is responsible for initiating this delete request? Is there any solution for this?"

**Comment by baselalali** [comment]
Fixed by updating decencies  

    ```
   <appium.version>8.5.1</appium.version>
        <selenium.version>4.12.1</selenium.version>
        <cucumber.version>7.14.0</cucumber.version>

```
