### ISSUE TITLE
Cannot find module 'appium-flutter-finder'

### ISSUE THREAD

**Issue by weetabixhands** [appium/appium-flutter-driver#575]
Hey there, 

I'm trying to follow the Node example [here](https://github.com/appium/appium-flutter-driver/blob/main/example/nodejs/src/index.js) and am getting the following error when I try to import `appium-flutter-finder`:

> Error: Cannot find module 'appium-flutter-finder'
> Require stack:
> - /Users/den/flutter_apps/appium_test/tests/test.js
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
>     at Module._load (node:internal/modules/cjs/loader:928:27)
>     at Module.require (node:internal/modules/cjs/loader:1149:19)
>     at require (node:internal/modules/helpers:121:18)
>     at Object.<anonymous> (/Users/den/flutter_apps/appium_test/tests/test.js:2:14)
>     at Module._compile (node:internal/modules/cjs/loader:1267:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
>     at Module.load (node:internal/modules/cjs/loader:1125:32)
>     at Module._load (node:internal/modules/cjs/loader:965:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/Users/den/flutter_apps/appium_test/tests/test.js' ]
> }

Am I missing something obvious or is there a known issue with `appium-flutter-finder` on Node?
I am running `Node v20.0.0`, `NPM v9.8.0` and `Appium 2.1.3`.
My full code for reference:

> const {remote} = require('webdriverio');
> const find = require('appium-flutter-finder');
> 
> const capabilities = {
>   platformName: 'iOS',
>   "appium:platformVersion": "16.4",
>   'appium:deviceName': 'iPhone 14',
>   'appium:automationName': 'flutter',
>   'appium:app': '/Users/den/flutter_apps/testing_app/build/ios/iphonesimulator/Runner.app',
> };
> 
> const wdOpts = {
>   hostname: process.env.APPIUM_HOST || 'localhost',
>   port: parseInt(process.env.APPIUM_PORT, 10) || 4723,
>   logLevel: 'info',
>   capabilities,
> };
> 
> async function runTest() {
>   const driver = await remote(wdOpts);
>   try {
>     await driver.execute('flutter:checkHealth');
>     await driver.getElementText(find.byText('Testing Sample'));
>   } finally {
>     await driver.pause(1000);
>     await driver.deleteSession();
>   }
> }
> 
> runTest().catch(console.error);

Any help would be appreciated, thanks.

**Comment by KazuCocoa** [comment]
What's about running `npm install` in https://github.com/appium/appium-flutter-driver/tree/main/example/nodejs and run `node`, and below require in the same directory?

```
> find = require('appium-flutter-finder');
{
  ancestor: [Function (anonymous)],
  bySemanticsLabel: [Function (anonymous)],
  byTooltip: [Function (anonymous)],
  byType: [Function (anonymous)],
  byValueKey: [Function (anonymous)],
  descendant: [Function (anonymous)],
  pageBack: [Function (anonymous)],
  byText: [Function (anonymous)]
}
```

**Comment by weetabixhands** [comment]
Yeah I'm an idiot. I hadn't added the dependencies to the `package.json` and then ran `npm install`. Thanks for the rubber ducking!
