### ISSUE TITLE
Driver not working when on imported package

### ISSUE THREAD

**Issue by jakeataofl** [appium/appium-flutter-driver#576]
Hello, been using appium-flutter-driver for all of our apps and been smooth-sailing since 👍 
We have a new project that is a little different from our existing ones that is causing automation struggles for my team.

We have 2 repositoryies:
RepositoryA which is the main app, has the main.dart and the command to enable flutter automation through the app.
RepositoryB which is a feature only that gets imported in RepositoryA, no main.dart on this repo.

RepositoryA has 3 screens: Screen1, Screen2, Screen3
RepositoryB has Screen4.

When we launch the app, we are able to navigate through RepositoryA's screens via automation, but upon reaching Screen4 (RepositoryB's), we can't anymore. We have defined keys on repositoryB as well, but seems everything we do automation related on this screen does nothing.

Attached the ff: pytest script converted to txt file, appium logs

[pytest_test.txt](https://github.com/appium/appium-flutter-driver/files/12694253/pytest_test.txt)

[Screen4-automation-not-working-appiumlogs.txt](https://github.com/appium/appium-flutter-driver/files/12694251/Screen4-automation-not-working-appiumlogs.txt)

Any insights are appreciated and please do let me know if more info is needed 😄

**Comment by KazuCocoa** [comment]
Does `enableFlutterDriverExtension()` need to be installed in the repository B side as well...?

**Comment by jakeataofl** [comment]
@KazuCocoa I'm not sure, it's being imported as a library to respositoryA.

And I only know that `enableFlutterDriverExtension()` is to be set in lib/main.dart which repositoryB doesn't have.

**Comment by jakeataofl** [comment]
https://github.com/appium/appium-flutter-driver/issues/181#issuecomment-1323684510

Did the trick for us. Thought the imported package was causing this since that was a difference we saw from all our other apps.
