### ISSUE TITLE
Appium can only find one element when detecting a list of elements with generated valuekeys

### ISSUE THREAD

**Issue by anikumar30** [appium/appium-flutter-driver#580]
I have a button(s) in my flutter app that will appear as many times as a given input; using it for a detecting bluetooth devices. So for every bluetooth device it finds, it has a connect button. 
To find this button on appium, I added keys that increments for each button that shows up. For example, 'connect1', 'connect2', etc. by adding this right below the button widget

_key: ValueKey('connect${index + 1}'),_

This does result in generating keys such as 'connect1', 'connect2', etc...

However, when I try to click each button and use find.byValuekey, it finds the first element but does not find the next element, and is left hanging. Has anyone had this issue before? Is there a workaround??

**Comment by KazuCocoa** [comment]
You could check if the expected element exists with `getRenderTree` in https://github.com/appium/appium-flutter-driver?tab=readme-ov-file#commands

If no expected element exists, it would be DartVM/Flutter side's issue.
