### ISSUE TITLE
Flutter Java. Finding nested elements (depth level greater than one)

### ISSUE THREAD

**Issue by sashkir7** [appium/appium-flutter-driver#584]
## Questions:
1. Does flutter driver support searching for large nesting (more than 2 elements)? 
For example, find MainView, in which find ButtonView, in which find Text (MainView --> ButtonVIew --> Text).
2. If it does, then how to correctly serialize the path to the element? 
So that the flutter driver parses and processes it correctly.

### 1. Library [javaflutterfinder](https://github.com/ashwithpoojary98/javaflutterfinder)
You [recommend](https://github.com/appium/appium-flutter-driver#java-implementation) it for use.
This library does not implement the logic of the [serialize()](https://github.com/ashwithpoojary98/javaflutterfinder/blob/c33db47c8ea916fec9e9bfeef1c4f528434b7eb8/src/main/java/io/github/ashwith/flutter/FlutterElement.java#L45-L60) method incorrectly.
Because of this, it is impossible to work with searching for elements using _byAncestor()_ and _byDescendant()_. 

For example, searching for an element in the parent:
```
FlutterElement element1 = finder.byText("Hello");
FlutterElement element2 = finder.byValueKey("World");
finder.byDescendant(element1, element2, true, true).click();
```
* The command is sent to the appium server:
`[debug] [FlutterDriver@88d8 (32134713)] Calling AppiumDriver.click() with args: ["eyJmaXJzdE1hdGNoT25seSI6InRydWUiLCJvZiI6ZmFsc2UsImZpbmRlclR5cGUiOiJEZXNjZW5kYW50IiwibWF0Y2hSb290IjoidHJ1ZSIsIm1hdGNoaW5nIjpmYWxzZX0=","32134713-2dac-42a4-84ec-2c8ac2aa6774"]`
* Where in the element locator the parent and child element information is lost:
`{"command":"tap","firstMatchOnly":"true","of":false,"finderType":"Descendant","matchRoot":"true","matching":false}`
* Flutter driver responds to this request with an error:
`{"isError":true,"response":"Uncaught extension error while executing tap: type 'bool' is not a subtype of type 'Map<String, dynamic>' in type cast\n#0      Descendant.deserialize (package:flutter_driver/src/common/find.dart:325:58)\n#1      DeserializeFinderFactory.deserializeFinder (package:flutter_driver/src/common/deserialization_factory.dart:32:44)\n#2      FlutterDriverExtension.deserializeFinder (package:flutter_driver/src/extension/extension.dart:405:18)\n#3      new CommandWithTarget.deserialize (package:flutter_driver/src/common/find.dart:30:30)\n#4      new Tap.deserialize (package:flutter_driver/src/common/gesture.dart:13:60)\n#5      DeserializeCommandFactory.deserializeCommand (package:flutter_driver/src/common/deserialization_factory.dart:56:30)\n#6      FlutterDriverExtension.deserializeCommand (package:flutter_driver/src/extension/extension.dart:425:18)\n#7      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:369:31)\n#8      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:936:32)\n<asynchronous suspension>\n","type":"_extensionType","method":"ext.flutter.driver"}`
* Here the behavior of the flutter driver is correct and understandable. Go next.

### 2. Library [appium-flutter-client](https://github.com/5v1988/appium-flutter-client)
You [recommend](https://github.com/appium/appium-flutter-driver#java-implementation) it for use.
Here, searching for elements using _byAncestor()_ and _byDescendant()_ works fine, but only at the **first level of nesting**.
For example, this command correctly searches for an element and clicks on it:
```
driver.findDescendantElement(
      driver.findElement(TEXT, "Hello"), 
      driver.findElement(TEXT, "World"), 
      true, 
      true
).click();
```
But when I want to use a deeper search, the flutter driver cannot parse the element locator and process the command. For example, the following command causes an error:
* Input command in appium:
`[debug] [FlutterDriver@f269 (e782d12c)] Calling AppiumDriver.execute() with args: ["flutter:waitFor",["eyJmaXJzdE1hdGNoT25seSI6InRydWUiLCJvZiI6IntcImZpbmRlclR5cGVcIjpcIkRlc2NlbmRhbnRcIixcImZpcnN0TWF0Y2hPbmx5XCI6dHJ1ZSxcIm1hdGNoUm9vdFwiOnRydWUsXCJvZlwiOntcImZpbmRlclR5cGVcIjpcIkJ5VHlwZVwiLFwidHlwZVwiOlwiQnV0dG9uVmlld1wifSxcIm1hdGNoaW5nXCI6e1wiZmluZGVyVHlwZVwiOlwiQnlUeXBlXCIsXCJ0eXBlXCI6XCJCdXR0b25cIn19IiwiZmluZGVyVHlwZSI6IkFuY2VzdG9yIiwibWF0Y2hSb290IjoidHJ1ZSIsIm1hdGNoaW5nIjoie1wiZmluZGVyVHlwZVwiOlwiQnlUeXBlXCIsXCJ0eXBlXCI6XCJNYWluVmlld1wifSJ9",1000],"e782d12c-e75f-4248-96d5-171ed5c10192"]`
* After decoding:
`{"command":"waitFor","firstMatchOnly":"true","of":"{\"finderType\":\"Descendant\",\"firstMatchOnly\":true,\"matchRoot\":true,\"of\":{\"finderType\":\"ByType\",\"type\":\"ButtonView\"},\"matching\":{\"finderType\":\"ByType\",\"type\":\"Button\"}}","finderType":"Ancestor","matchRoot":"true","matching":"{\"finderType\":\"ByType\",\"type\":\"MainView\"}","timeout":1000}`
* Flutter driver could not recognize the element:
`{"isError":true,"response":"Uncaught extension error while executing waitFor: type 'bool' is not a subtype of type 'String' in type cast\n#0      new LinkedHashMap.from.<anonymous closure> (dart:collection/linked_hash_map.dart:187:26)\n#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)\n#2      new LinkedHashMap.from (dart:collection/linked_hash_map.dart:186:11)\n#3      Ancestor.deserialize (package:flutter_driver/src/common/find.dart:380:9)\n#4      DeserializeFinderFactory.deserializeFinder (package:flutter_driver/src/common/deserialization_factory.dart:33:40)\n#5      FlutterDriverExtension.deserializeFinder (package:flutter_driver/src/extension/extension.dart:405:18)\n#6      new CommandWithTarget.deserialize (package:flutter_driver/src/common/find.dart:30:30)\n#7      new WaitFor.deserialize (package:flutter_driver/src/common/find.dart:58:64)\n#8      DeserializeCommandFactory.deserializeCommand (package:flutter_driver/src/common/deserialization_factory.dart:57:38)\n#9      FlutterDriverExtension.deserializeCommand (package:flutter_driver/src/extension/extension.dart:425:18)\n#10     FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:369:31)\n#11     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:936:32)\n<asynchronous suspension>\n","type":"_extensionType","method":"ext.flutter.driver"}`

### 3. Examples of Java tests in this [repository](https://github.com/appium/appium-flutter-driver/tree/main/example/java/src/test/java/example/appium)
[Here](https://github.com/appium/appium-flutter-driver/blob/main/example/java/src/test/java/example/appium/FlutterTest.java#L107-L115) is an example that interests me. And apparently this code should work. 
But unfortunately, due to dependency issues, I can't run it to test it personally.

**Comment by sashkir7** [comment]
@KazuCocoa good day! Can you help me, please

**Comment by williampearl** [comment]
I believe both this issue and mine (https://github.com/appium/appium-flutter-driver/issues/586) are related.

**Comment by KazuCocoa** [comment]
`"of":false` in the first one was probably not correct.

for the second one, it looks correct, but maybe the request was something wrong? https://github.com/flutter/flutter/blob/master/packages/flutter_driver/lib/src/common/find.dart#L323 is probably the receiver.  Should `firstMatchOnly` be string?

**Comment by KazuCocoa** [comment]
I have updated https://github.com/appium/appium-flutter-driver/tree/main/finder , but these client authors also need to do the same update for Java. Thank you.

**Comment by sashkir7** [comment]
Update solved this issue!
Thank you @KazuCocoa
