### ISSUE TITLE
Updating appium-xcuitest-driver to the latest 5.x version

### ISSUE THREAD

**Issue by mark-tilman-yolabs** [appium/appium-flutter-driver#587]
I added a comment to the PR opened by dependabot just asking what the timeline is to update to a newer version of `appium-xcuitest-driver`:
* https://github.com/appium/appium-flutter-driver/pull/581#issuecomment-1751488336

Specifically, I was looking for version `5.4.0` or later to try out the `mobile: clearApp` script.
* https://github.com/appium/appium-xcuitest-driver/pull/2031

Currently, we are pinned to `5.2.0`.  That dependabot PR as it stands would specifically pin to `5.4.1` if it is merged as-is, but I assume we would probably want to use `^5.6.0` so it uses the latest 5.x version going forward...

I figured I would add my question as an issue instead of just commenting on the PR, since it might be closed and replaced by a newer dependabot PR and I wasn't sure how often an automated PR would be checked for comments. 😄 

Please let me know if there is a better approach I should have used instead.

Thanks!

**Comment by KazuCocoa** [comment]
Sure, let me merge and push a new version

**Comment by mark-tilman-yolabs** [comment]
Great!  I confirmed I could run `mobile: clearApp` on iOS now.

Thanks!
