### ISSUE TITLE
Cannot click the ListView elements

### ISSUE THREAD

**Issue by Nowshin23** [appium/appium-flutter-driver#597]
Hi Kazuaki Matsuo,

We have a ListView in our flutter Application. I want to click the First Element of the ListView. Tried to do it in several ways but couldn't find the solution. Could you please help me how to do this? I am sharing a screenshot from our application so that you can understand the situation better. 

![image](https://github.com/appium/appium-flutter-driver/assets/133006781/d151bc67-c385-45c4-b8c8-d554b49821aa)

**Comment by KazuCocoa** [comment]
if it is a flutter element, afaik, the only way is to put a unique key in the element.
Or https://github.com/appium/appium-flutter-driver?tab=readme-ov-file#appium-flutter-driver-or-appium-uiautomator2xcuitest-driver in uia2 driver may help

**Comment by KazuCocoa** [comment]
If it failed in FLUTTER context, UI2 with NATIVE_APP context would be an alternative method for it.
