### ISSUE TITLE
Cannot send keyboard keys

### ISSUE THREAD

**Issue by anesana** [appium/appium-flutter-driver#602]
Im using appium-flutter-driver with a robot framework library. Im trying to send a key using Press Keycode which is the implementation of: driver.press_keycode(key code, metastate). 
On the console log I have the following error:

WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Command not support: "mobile: pressKey"
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Command not support: "mobile: pressKey"
    at getResponseForW3CError (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1092:9)
    at asyncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:491:57)

on the appium server console I have the following:

[debug] [FlutterDriver@a881 (92bb8268)] Calling AppiumDriver.execute() with args: ["mobile: pressKey",[{"keycode":"66"}],"92bb8268-ea8f-48bc-8226-465d16f1389b"]
[debug] [FlutterDriver] Executing Flutter driver command 'execute'
[debug] [FlutterDriver@a881 (92bb8268)] Encountered internal error running command: Error: Command not support: "mobile: pressKey"

Im using Appium v2.1.3 and appium-flutter-driver v2.1.0

Can you help?

**Comment by KazuCocoa** [comment]
Except for https://github.com/appium/appium-flutter-driver?tab=readme-ov-file#commands commands, you need to change the context to NATIVE_APP like https://github.com/appium/appium-flutter-driver?tab=readme-ov-file#context-management . Then, the `mobile:` command will work

**Comment by anesana** [comment]
Thanks @KazuCocoa  for your quick answer ! Will try to implemente that!

**Comment by anesana** [comment]
I've implemented what you suggested, and I was able to send the 'enter' key, the problem now is that somehow this key is being "ignored" by the application, I think its related to the problems reported on these tickets: https://github.com/appium/appium-flutter-driver/issues/40
https://github.com/flutter/flutter/issues/15415

Do you have any suggestion on how to fix this issue ?

**Comment by KazuCocoa** [comment]
Hn, then, it seems like the flutter_driver (developed by the Flutter team) 's limitation. If so, the only way to use keyboard is probably uiautomator2 driver with non-enableFlutterDriverExtension build (so this driver may not work for the use case)

**Comment by KazuCocoa** [comment]
Hm, according to https://github.com/appium/appium-flutter-driver/issues/246 , sending key code via adb worked?
Then, you could do the same thing via https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#mobile-shell
