### ISSUE TITLE
Does the Appium Flutter Driver support accessibility testing?

### ISSUE THREAD

**Issue by pothurajtharun** [appium/appium-flutter-driver#610]
Hi All,

I was automating flutter mobile app using `appium-flutter-driver`. It works great. Now I would like to perform accessibility testing for flutter mobile app for both iOS and Android. Does `appium-flutter-driver` supports accessibility testing ? 

Please help me with some pointers.

Thanks!

**Comment by KazuCocoa** [comment]
What kind of behavior is expected? For example, if an element has content-description in Android, such a thing?
Then, you can check with uia2/xcuitest driver rather than this since uia2/xcuitest can find elements -> these elements are exposed for accessibility functionality (usually)

**Comment by KazuCocoa** [comment]
Then, if you could find these elements with accessibility id locator with NATIVE_APP context in this driver or UIA2/XCUITest drivers, OS usually can detect them for Voice over etc.
Font size etc depends on https://api.flutter.dev/flutter/flutter_driver/flutter_driver-library.html that is provided by Flutter and this driver depends on that.
