### ISSUE TITLE
Is there any "waitForTapable" analog but for element's visibility?

### ISSUE THREAD

**Issue by Vladeezyy** [appium/appium-flutter-driver#612]
driver's methods for visibility are not working for me, as I understand that's because of flutter app's element nature and I need to implement something like waitForVisibility, can I do it somehow ?

**Comment by KazuCocoa** [comment]
Afaik, no, since https://api.flutter.dev/flutter/flutter_driver/flutter_driver-library.html (this driver's dependent lib) does not provide such functionality. So far, tappable or just wait for (if an element exists) is what can do in the FLUTTER context.
