### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 119 Current browser version is 118.0.0.0 with package name com.reqi.will

### ISSUE THREAD

**Issue by DhakshathAmin** [appium/appium-flutter-driver#618]
### I faced following challenges and would really like to know "How task it getting done in backend..!"

When I launched Flutter App as **switched context** to **WEBVIEW** got the following error : 

`An unknown server-side error occurred while processing the command. Original error: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 119 Current browser version is 118.0.0.0 with package name com.reqi.will`

I crossed verified with my Mobile Browser version which was at `119.xxx.xx` and chromDriver Version (_which is located @ /Users/dhakshath/.appium/node_modules/appium-flutter-driver/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac is `118.xxx.xx`_)

This is known as currrent appium-flutter-driver is supporting `118.xxx.xx` in latest version and I have to manually replace it,  upon ...

manually downloaded the chromeDriver from https://sites.google.com/chromium.org/driver/ and pasted it in location _/Users/dhakshath/.appium/node_modules/appium-flutter-driver/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac_, also has to give permission in Security&Privacy and got below error 

`An unknown server-side error occurred while processing the command. Original error: No Chromedriver found that can automate Chrome '118.0.5993.70'. You could also try to enable automated chromedrivers download as a possible workaround.`

**QUESTION ** : I see chromeDriver inside appium-flutter-driver is in some kind of **Document** type and manually downloaded ChromeDriver is in **UnixExecutable** Type. 
1. Why the difference?
2. What does this mean "Current browser version is 118.0.0.0 with package name com.reqi.will`"?

**Comment by DhakshathAmin** [comment]
I dont see any kind of difference between Mac & windows.

**Comment by KazuCocoa** [comment]
Please attache the full appium log with `chromedriver_autodownload` flag as https://github.com/appium/appium-flutter-driver/issues/618#issuecomment-1802885928

The error means your app used chrome 118 but your running env did not have the version.

**Comment by DhakshathAmin** [comment]
Issue resolved. Closing ticket
