### ISSUE TITLE
Real iOS device automation is getting "xcodebuild failed with code 70" error with "automationName: Flutter" setting, however, XCUITest is working fine

### ISSUE THREAD

**Issue by ozgurkaya-mobven** [appium/appium-flutter-driver#633]
Hi to all,

I am running on a real iOS device and it's working with automationName: XCUITest setting. When I want to change this to automationName: Flutter it's getting an error. "Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70"

What should be the problem, Am I missing something?

{
  "appium:automationName": "XCUITest",
  "appium:app": "<my ipa path>",
  "appium:udid": "",
  "appium:deviceName": "",
  "appium:autoAcceptAlerts": true,
  "appium:autoDissmissAlerts": true,
  "platformName": "iOS",
}

Test framework: WebdriverIO (typescript) latest
MacOS: Sonoma 14.0
Xcode 15.0
NodeJS v20.8.0
Appium server: 2.0.1
✔ Listing available drivers
- uiautomator2@2.29.11 [installed (npm)]
- espresso@2.25.9 [installed (npm)]
- mac2@1.8.2 [installed (npm)]
- flutter@2.2.0 [installed (npm)]
- xcuitest@5.8.2 [installed (npm)]

The target device is iPhone 14 pro max - iOS 17 (Apple developer signed provisioning profile for WebDriverAgentRunner). I also tried with the iPhone 8, 12 pro and much more phones, same result.

**Comment by KazuCocoa** [comment]
Please attach the full appium log with `appium:showXcodeLog` appium capability.

**Comment by hakantektas** [comment]
I started webdriveragentRunner from the folder specified in the error log, installed the certificate, and when I wanted to run the test again, the error message changed.



Failed to create session. An unknown server-side error occurred while processing the command. Original error: Cannot determine the Dart Observatory URL after 10 retries. Original error: No observatory URL matching to '/(Observatory listening on |An Observatory debugger and profiler on\s.+\sis available at: |The Dart VM service is listening on )((http|\/\/)[a-zA-Z0-9:/=_\-.\[\]]+)/' was found in the device log. Please make sure the application under test is configured properly according to https://github.com/appium-userland/appium-flutter-driver#usage and that it does not crash on startup.

**Comment by KazuCocoa** [comment]
It usually means the app under test did not print any observatory URL.
https://github.com/appium/appium-flutter-driver?tab=readme-ov-file#usage-and-requirement
Was the app under test built with `profile` mode?

`showIOSLog` caps would help to check if the system log prints the observatory URL

**Comment by tc-mnunez** [comment]
any news from this issue?

**Comment by ozgurkaya-mobven** [comment]
Appium flutter driver uses a different WebDriverAgent Xcode project, that was the problem. It has been fixed, after we modified app signing for this WebDriverAgent project. Thanks a lot. If there is a way please use a "shared Webdriveragent project" on the Appium server project. Best regards.
