### ISSUE TITLE
How to perform waitFor on appium flutter driver java

### ISSUE THREAD

**Issue by mazis0** [appium/appium-flutter-driver#639]
Hello , how to perform command waitFor on appium flutter driver java?

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-flutter-driver/blob/330ab4b9745b36d84c3865c5d171eeb03cc6d558/example/java/src/test/java/example/appium/FlutterTest.java would help

**Comment by mazis0** [comment]
@KazuCocoa i have issue after perform command waitFor

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot execute command waitFor, server reponse {
  "isError": true,
  "response": "Uncaught extension error while executing waitFor: 'package:flutter_driver/src/extension/extension.dart': Failed assertion: line 364 pos 14: 'WidgetsBinding.instance.isRootWidgetAttached || !command.requiresRootWidgetAttached': No root widget is attached; have you remembered to call runApp()?\n#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)\n#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)\n#2      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:364:14)\n#3      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:944:32)\n<asynchronous suspension>\n#4      _runExtension.<anonymous closure> (dart:developer-patch/developer.dart:112:11)\n<asynchronous suspension>\n",
  "type": "_extensionType",
  "method": "ext.flutter.driver"
}

how to solve this issue? thanks for help

**Comment by KazuCocoa** [comment]
Could it be related to https://stackoverflow.com/questions/57861495/flutter-flutter-driver-error-message-and-app-screen-stays-black-while-testing ?
