### ISSUE TITLE
Appium opens the flutter application and then hangs, says port is busy

### ISSUE THREAD

**Issue by anikumar30** [appium/appium-flutter-driver#642]
I have this issue where appium opens my flutter application on a real ipad, and then hangs with the following log. It sucessfully downloads webdriver, only for it to say the port is busy. 

debug] [XCUITestDriver@4640 (81100193)] WebDriverAgent information:
[debug] [XCUITestDriver@4640 (81100193)] {
[debug] [XCUITestDriver@4640 (81100193)]   "message": "WebDriverAgent is ready to accept commands",
[debug] [XCUITestDriver@4640 (81100193)]   "state": "success",
[debug] [XCUITestDriver@4640 (81100193)]   "os": {
[debug] [XCUITestDriver@4640 (81100193)]     "testmanagerdVersion": 28,
[debug] [XCUITestDriver@4640 (81100193)]     "name": "iPadOS",
[debug] [XCUITestDriver@4640 (81100193)]     "sdkVersion": "16.4",
[debug] [XCUITestDriver@4640 (81100193)]     "version": "16.6.1"
[debug] [XCUITestDriver@4640 (81100193)]   },
[debug] [XCUITestDriver@4640 (81100193)]   "ios": {
[debug] [XCUITestDriver@4640 (81100193)]     "ip": "192.168.1.201"
[debug] [XCUITestDriver@4640 (81100193)]   },
[debug] [XCUITestDriver@4640 (81100193)]   "ready": true,
[debug] [XCUITestDriver@4640 (81100193)]   "build": {
[debug] [XCUITestDriver@4640 (81100193)]     "upgradedAt": "1691701695821",
[debug] [XCUITestDriver@4640 (81100193)]     "time": "Oct 20 2023 14:17:06",
[debug] [XCUITestDriver@4640 (81100193)]     "productBundleIdentifier": "XXXXXXX.testing.WebDriverAgentRunner"
[debug] [XCUITestDriver@4640 (81100193)]   }
[debug] [XCUITestDriver@4640 (81100193)] }
[debug] [XCUITestDriver@4640 (81100193)] WebDriverAgent successfully started after 9468ms
[debug] [XCUITestDriver@4640 (81100193)] Event 'wdaSessionAttempted' logged at 1702843814892 (15:10:14 GMT-0500 (Eastern Standard Time))
[debug] [XCUITestDriver@4640 (81100193)] Sending createSession command to WDA
[debug] [XCUITestDriver@4640 (81100193)] Matched '/session' to command name 'createSession'
[debug] [XCUITestDriver@4640 (81100193)] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.testing.patientHostApp","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true,"shouldTerminateApp":true,"forceAppLaunch":true,"useNativeCachingStrategy":true,"forceSimulatorSoftwareKeyboardPresence":true}],"alwaysMatch":{}}}
[debug] [XCUITestDriver@4640 (81100193)] Got response with status 200: {"value":{"sessionId":"B62F83A4-68F5-4C9C-9315-719B8B41E68B","capabilities":{"device":"ipad","browserName":"Patient Host App","sdkVersion":"16.6.1","CFBundleIdentifier":"com.testing.patientHostApp"}},"sessionId":"B62F83A4-68F5-4C9C-9315-719B8B41E68B"}
[XCUITestDriver@4640 (81100193)] Determined the downstream protocol as 'W3C'
[debug] [XCUITestDriver@4640 (81100193)] Event 'wdaSessionStarted' logged at 1702843817131 (15:10:17 GMT-0500 (Eastern Standard Time))
[debug] [XCUITestDriver@4640 (81100193)] Event 'wdaStarted' logged at 1702843817131 (15:10:17 GMT-0500 (Eastern Standard Time))
[debug] [BaseDriver] The value of 'elementResponseAttributes' setting did not change. Skipping the update for it
[debug] [BaseDriver] The value of 'shouldUseCompactResponses' setting did not change. Skipping the update for it
[FlutterDriver] Attempt #1
[FlutterDriver] Running on iOS real device
[FlutterDriver] Port forwarding to: 59491
[FlutterDriver] Connecting to Dart Observatory: ws://127.0.0.1:59491/p6YbQqzzpPs=/ws
[FlutterDriver] Connecting to ws://127.0.0.1:59491/p6YbQqzzpPs=/ws
[FlutterDriver] Listing all isolates: [{"type":"@Isolate","id":"isolates/3935125082630639","name":"main","number":"3935125082630639","isSystemIsolate":false,"isolateGroupId":"isolateGroups/5315755538372737"}]
[FlutterDriver] "ext.flutter.driver" is not found in "extensionRPCs" ["ext.ui.window.impellerEnabled","ext.dart.io.getHttpEnableTimelineLogging","ext.dart.io.setHttpEnableTimelineLogging","ext.dart.io.httpEnableTimelineLogging","ext.dart.io.getSocketProfile","ext.dart.io.startSocketProfiling","ext.dart.io.pauseSocketProfiling","ext.dart.io.socketProfilingEnabled","ext.dart.io.clearSocketProfile","ext.dart.io.getVersion","ext.dart.io.getHttpProfile","ext.dart.io.getHttpProfileRequest","ext.dart.io.clearHttpProfile","ext.flutter.exit","ext.flutter.connectedVmServiceUri","ext.flutter.activeDevToolsServerAddress","ext.flutter.timeDilation","ext.flutter.debugDumpRenderTree","ext.flutter.debugDumpSemanticsTreeInTraversalOrder","ext.flutter.debugDumpSemanticsTreeInInverseHitTestOrder","ext.flutter.profileRenderObjectPaints","ext.flutter.profileRenderObjectLayouts","ext.flutter.debugDumpApp","ext.flutter.debugDumpFocusTree","ext.flutter.showPerformanceOverlay","ext.flutter.didSendFirstFrameEvent","ext.flutter.didSendFirstFrameRasterizedEvent","ext.flutter.profileWidgetBuilds","ext.flutter.profileUserWidgetBuilds","ext.dart.io.getOpenFiles","ext.dart.io.getOpenFileById"]
[FlutterDriver] Waiting 3 seconds before trying...
[FlutterDriver] Attempt #2
[FlutterDriver] Running on iOS real device
[FlutterDriver] Port #59491 is busy. Did you quit the previous driver session(s) properly?
[FlutterDriver] Did not know how to release port #59491 in 15004ms
[debug] [FlutterDriver] Error: The port :59491 is occupied by an other process. You can either quit that process or select another free port.
[debug] [FlutterDriver]     at waitForPortIsAvailable (/Users/ani/.appium/node_modules/appium-flutter-driver/lib/sessions/ios.ts:83:11)
[debug] [FlutterDriver]     at getObservatoryWsUri (/Users/ani/.appium/node_modules/appium-flutter-driver/lib/sessions/ios.ts:111:3)
[debug] [FlutterDriver]     at connectSocket (/Users/ani/.appium/node_modules/appium-flutter-driver/lib/sessions/observatory.ts:33:28)
[debug] [FlutterDriver]     at async Promise.all (index 1)
[debug] [FlutterDriver]     at FlutterDriver.createSession (/Users/ani/.appium/node_modules/appium-flutter-driver/lib/sessions/session.ts:36:47)
[debug] [FlutterDriver]     at AppiumDriver.createSession (/opt/homebrew/lib/node_modules/appium/lib/appium.js:374:35)
[FlutterDriver] Connecting to Dart Observatory: undefined
[FlutterDriver] {}
[FlutterDriver] Check Dart Observatory URI no URI found in the device log
[FlutterDriver] Waiting 3 seconds before trying...
[FlutterDriver] Attempt #3
[FlutterDriver] Running on iOS real device
[FlutterDriver] Port #59491 is busy. Did you quit the previous driver session(s) properly?
[FlutterDriver] Did not know how to release port #59491 in 15002ms
[debug] [FlutterDriver] Error: The port :59491 is occupied by an other process. You can either quit that process or select another free port.
[debug] [FlutterDriver]     at waitForPortIsAvailable (/Users/ani/.appium/node_modules/appium-flutter-driver/lib/sessions/ios.ts:83:11)
[debug] [FlutterDriver]     at getObservatoryWsUri (/Users/ani/.appium/node_modules/appium-flutter-driver/lib/sessions/ios.ts:111:3)
[debug] [FlutterDriver]     at connectSocket (/Users/ani/.appium/node_modules/appium-flutter-driver/lib/sessions/observatory.ts:33:28)
[debug] [FlutterDriver]     at async Promise.all (index 1)
[debug] [FlutterDriver]     at FlutterDriver.createSession (/Users/ani/.appium/node_modules/appium-flutter-driver/lib/sessions/session.ts:36:47)
[debug] [FlutterDriver]     at AppiumDriver.createSession (/opt/homebrew/lib/node_modules/appium/lib/appium.js:374:35)
[FlutterDriver] Connecting to Dart Observatory: undefined
[FlutterDriver] {}
[FlutterDriver] Check Dart Observatory URI no URI found in the device log
[FlutterDriver] Waiting 3 seconds before trying...
[FlutterDriver] Attempt #4
[FlutterDriver] Running on iOS real device
[FlutterDriver] Port #59491 is busy. Did you quit the previous driver session(s) properly?
[FlutterDriver] Did not know how to release port #59491 in 15002ms
[debug] [FlutterDriver] Error: The port :59491 is occupied by an other process. You can either quit that process or select another free port.
[debug] [FlutterDriver]     at waitForPortIsAvailable (/Users/ani/.appium/node_modules/appium-flutter-driver/lib/sessions/ios.ts:83:11)
[debug] [FlutterDriver]     at getObservatoryWsUri (/Users/ani/.appium/node_modules/appium-flutter-driver/lib/sessions/ios.ts:111:3)
[debug] [FlutterDriver]     at connectSocket (/Users/ani/.appium/node_modules/appium-flutter-driver/lib/sessions/observatory.ts:33:28)
[debug] [FlutterDriver]     at async Promise.all (index 1)
[debug] [FlutterDriver]     at FlutterDriver.createSession (/Users/ani/.appium/node_modules/appium-flutter-driver/lib/sessions/session.ts:36:47)
[debug] [FlutterDriver]     at AppiumDriver.createSession (/opt/homebrew/lib/node_modules/appium/lib/appium.js:374:35)
[FlutterDriver] Connecting to Dart Observatory: undefined
[FlutterDriver] {}
[FlutterDriver] Check Dart Observatory URI no URI found in the device log
[FlutterDriver] Waiting 3 seconds before trying...
[FlutterDriver] Attempt #5
[FlutterDriver] Running on iOS real device
[FlutterDriver] Port #59491 is busy. Did you quit the previous driver session(s) properly?
[FlutterDriver] Did not know how to release port #59491 in 15002ms
[debug] [FlutterDriver] Error: The port :59491 is occupied by an other process. You can either quit that process or select another free port.
[debug] [FlutterDriver]     at waitForPortIsAvailable (/Users/ani/.appium/node_modules/appium-flutter-driver/lib/sessions/ios.ts:83:11)
[debug] [FlutterDriver]     at getObservatoryWsUri (/Users/ani/.appium/node_modules/appium-flutter-driver/lib/sessions/ios.ts:111:3)
[debug] [FlutterDriver]     at connectSocket (/Users/ani/.appium/node_modules/appium-flutter-driver/lib/sessions/observatory.ts:33:28)
[debug] [FlutterDriver]     at async Promise.all (index 1)
[debug] [FlutterDriver]     at FlutterDriver.createSession (/Users/ani/.appium/node_modules/appium-flutter-driver/lib/sessions/session.ts:36:47)
[debug] [FlutterDriver]     at AppiumDriver.createSession (/opt/homebrew/lib/node_modules/appium/lib/appium.js:374:35)

**Comment by KazuCocoa** [comment]
Please attach the full appium log. I guess that was fixed in https://github.com/appium/appium-flutter-driver/blob/main/driver/CHANGELOG.md#223

**Comment by KazuCocoa** [comment]
Closing the ticket as no response.
