### ISSUE TITLE
driver.context("Native_APP") no longer works in io.appium java-client 9.0

### ISSUE THREAD

**Issue by zeinmuhammad25** [appium/appium-flutter-driver#644]
I changed the java-client version to 9.0.0 which was originally version 7.6.1 which previously could use driver.context("Native_APP") to change the apps context to native on Flutter apps. please tell me the changes in java client 9.0.0 to change the context to native

thanks.

**Comment by KazuCocoa** [comment]
Please attach the full appium server log. I guess you should set `NATIVE_APP` (case sensitive)

The client has migration guides.  They could help I guess.

https://github.com/appium/java-client?tab=readme-ov-file#v8-to-v9-migration
https://github.com/appium/java-client?tab=readme-ov-file#v7-to-v8-migration
