### ISSUE TITLE
Cannot find item with By.Id in android into popup request permission in android device

### ISSUE THREAD

**Issue by apatheticL** [appium/appium-flutter-driver#654]
I have a problem when i call function find_element(By.Id, 'com.android.permissioncontroller:id/permission_allow_button') then it show error  in this link https://gist.github.com/apatheticL/0bea475d440c2e99c0a42fd350081205
this is my code 
my base function 

```
def find_element(self, locator):
        print(locator)
        try:
            return self.driver.find_element(*locator)
        except:
            self.handle_exception()
            # self.find_element(locator)
            return self.driver.find_element(*locator)

   def find_element_and_click(self, locator):
        print("click")
        try:
            self.find_element(locator).click()
        except:
            self.handle_exception()
            self.find_element(locator).click()
```

my call function 
```
    continue_button = (By.ID, 'com.android.permissioncontroller:id/permission_allow_button')
            self.find_element_and_click(self.continue_button)

```
value of seft  send into base funtion is 
```
/// library 
from appium.webdriver import Remote
from appium.webdriver.webdriver import WebDriver 

 clss.driver = Remote('http://localhost:4723', options=capabilities_options)
```

Please help me fix it. Thank so much.

**Comment by KazuCocoa** [comment]
I would switch the context to interact with elements outside Flutter https://github.com/appium/appium-flutter-driver?tab=readme-ov-file#context-management

**Comment by apatheticL** [comment]
Thank you, but I want to know what I should do now to pass this error. I'm waiting for you to update the new version of the library or do I need to fix anything in my code? 
I looked at the example (python) but couldn't find the config section to change the context

**Comment by KazuCocoa** [comment]
It is client side update only.

For python, https://github.com/appium/python-client/blob/92583ce39003b740bb5e57bbf2114d283d884d22/test/functional/android/context_switching_tests.py#L68 is the usage to switch the context.
https://appium.github.io/python-client-sphinx/webdriver.html#webdriver.switch_to.MobileSwitchTo.context

You would need to switch the context with NATIVE_APP to interact with non-Flutter elements before interacting with them since system permission is out of control by Flutter.

**Comment by apatheticL** [comment]
Thank so much. My problem is fixed.
