### ISSUE TITLE
npm command 'install --save-dev --no-progress --no-audit appium-flutter-driver --json' failed with code 1.

### ISSUE THREAD

**Issue by tangsai1993** [appium/appium-flutter-driver#664]
Installing Flutter Driver Error：npm command 'install --save-dev --no-progress --no-audit appium-flutter-driver --json' failed with code 1.
Detailed error message:

C:\Users\simon>appium driver install --source=npm appium-flutter-driver
√ Checking if 'appium-flutter-driver' is compatible
× Installing 'appium-flutter-driver'
Error: × Encountered an error when installing package: npm command 'install --save-dev --no-progress --no-audit appium-flutter-driver --json' failed with code 1.

STDOUT:
{
  "error": {
    "code": 1,
    "summary": "command failed",
    "detail": "C:\\Windows\\system32\\cmd.exe /d /s /c node install-npm.js\n[17:21:08] Error installing Chromedriver: read ECONNRESET\n[17:21:08] Error: read ECONNRESET\n    at Function.AxiosError.from (C:\\Users\\simon\\node_modules\\appium-flutter-driver\\node_modules\\appium-uiautomator2-driver\\node_modules\\axios\\lib\\core\\AxiosError.js:89:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\simon\\node_modules\\appium-flutter-driver\\node_modules\\appium-uiautomator2-driver\\node_modules\\axios\\lib\\adapters\\http.js:610:25)\n    at RedirectableRequest.emit (node:events:530:35)\n    at ClientRequest.eventHandlers.<computed> (C:\\Users\\simon\\node_modules\\appium-flutter-driver\\node_modules\\appium-uiautomator2-driver\\node_modules\\follow-redirects\\index.js:38:24)\n    at ClientRequest.emit (node:events:518:28)\n    at TLSSocket.socketErrorListener (node:_http_client:495:9)\n    at TLSSocket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (C:\\Users\\simon\\node_modules\\appium-flutter-driver\\node_modules\\appium-uiautomator2-driver\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at retrieveData (C:\\Users\\simon\\node_modules\\appium-flutter-driver\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-chromedriver\\lib\\utils.js:92:5)\n[17:21:08] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable."
  }
}

STDERR:
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\simon\\node_modules\\appium-flutter-driver\\node_modules',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\simon\node_modules\appium-flutter-driver\node_modules\appium-xcuitest-driver\node_modules\@appium\base-driver\node_modules\axios'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\simon\\node_modules\\appium-flutter-driver\\node_modules\\appium-xcuitest-driver\\node_modules\\@appium\\base-driver\\node_modules\\axios'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\simon\\node_modules\\appium-flutter-driver\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\simon\node_modules\appium-flutter-driver\node_modules\appium-uiautomator2-driver\node_modules\appium\node_modules\axios'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\simon\\node_modules\\appium-flutter-driver\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium\\node_modules\\axios'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\simon\\node_modules\\appium-flutter-driver',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\simon\node_modules\appium-flutter-driver\node_modules\appium-uiautomator2-driver\node_modules\appium'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\simon\\node_modules\\appium-flutter-driver\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\simon\\node_modules\\appium-flutter-driver',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\simon\node_modules\appium-flutter-driver\node_modules\appium-xcuitest-driver'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\simon\\node_modules\\appium-flutter-driver\\node_modules\\appium-xcuitest-driver'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\simon\\node_modules\\appium-flutter-driver\\node_modules\\appium-xcuitest-driver',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\simon\node_modules\appium-flutter-driver\node_modules\appium-xcuitest-driver'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\simon\\node_modules\\appium-flutter-driver\\node_modules\\appium-xcuitest-driver'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\simon\node_modules\appium-flutter-driver\node_modules\appium-uiautomator2-driver\node_modules\appium-chromedriver
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node install-npm.js
npm ERR! [17:21:08] Error installing Chromedriver: read ECONNRESET
npm ERR! [17:21:08] Error: read ECONNRESET
npm ERR!     at Function.AxiosError.from (C:\Users\simon\node_modules\appium-flutter-driver\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\core\AxiosError.js:89:14)
npm ERR!     at RedirectableRequest.handleRequestError (C:\Users\simon\node_modules\appium-flutter-driver\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\adapters\http.js:610:25)
npm ERR!     at RedirectableRequest.emit (node:events:530:35)
npm ERR!     at ClientRequest.eventHandlers.<computed> (C:\Users\simon\node_modules\appium-flutter-driver\node_modules\appium-uiautomator2-driver\node_modules\follow-redirects\index.js:38:24)
npm ERR!     at ClientRequest.emit (node:events:518:28)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:495:9)
npm ERR!     at TLSSocket.emit (node:events:518:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:169:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR!     at Axios.request (C:\Users\simon\node_modules\appium-flutter-driver\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\core\Axios.js:45:41)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR!     at retrieveData (C:\Users\simon\node_modules\appium-flutter-driver\node_modules\appium-uiautomator2-driver\node_modules\appium-chromedriver\lib\utils.js:92:5)
npm ERR! [17:21:08] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable.

npm ERR! A complete log of this run can be found in: E:\Program Files\nodejs\node_cache\_logs\2024-02-26T09_20_59_260Z-debug-0.log

C:\Users\simon>

**Comment by KazuCocoa** [comment]
It looks like your env had an issue in installing chromedriver. `APPIUM_SKIP_CHROMEDRIVER_INSTALL` environment variable would help.
https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#troubleshooting-chromedriver-download-issues

**Comment by tangsai1993** [comment]
> 看起来您的env在安装chromedriver时遇到了问题。`APPIUM_SKIP_CHROMEDRIVER_INSTALL`环境变量会有所帮助。 [https://github.com/appium/appium-uiautomator2-driver?tab = readme-ov-file #疑难解答-chrome driver-下载-问题](https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#troubleshooting-chromedriver-download-issues)

Solved. Thank you

**Comment by tangsai1993** [comment]
设置set APPIUM_SKIP_CHROMEDRIVER_INSTALL=1
