### ISSUE TITLE
How long will appium-flutter-driver 1.23.0/older 1.x.x versions) be supported?

### ISSUE THREAD

**Issue by kvgana** [appium/appium-flutter-driver#667]
Hi  @KazuCocoa 
How long will appium-flutter-driver 1.23.0/1.21.0  be supported? Can we continue using it ? if yes, for how long?
Or should we already move to using appium-flutter-driver 2.5.0 with uiautomator and xcuitest.

Thanks!

**Comment by KazuCocoa** [comment]
We don't apply any patches to older versions, so the answer is it depends on your test target. If your test target requires newer driver versions, the older driver version won't work. e.g. newer iOS versions that works only with newer XCUITest driver dependencies
