### ISSUE TITLE
how to automate check button enabled in Flutter ??

### ISSUE THREAD

**Issue by pornpawit08** [appium/appium-flutter-driver#693]
I need fucntion to check button enabled  (Python)

**Comment by Tegardoa** [comment]
I usually declare `ValueKey` in different state in my .dart file for example:
`ElevatedButton( key: isDisabled ? ValueKey('disabled-button') : ValueKey('enabled-button' )`

In my automation for example in js:
```
try { 
    button_state = 'disabled';
    await driver.execute('flutter:waitFor', finder.byValueKey('disabled-button'), 3000);
} catch (e) {
    try {
        button_state = 'enabled';
        await driver.execute('flutter:waitFor', finder.byValueKey('enabled-button'), 3000);
    } catch (innerE) {
        throw new Error('Button is not found');
    }
}
```

Maybe you can write like this in python:
```
try:
    button_state = 'disabled'
    driver.execute_script('flutter:waitFor', finder.byValueKey('disabled-button'), 3000);
except TimeoutException as e:
    try:
        button_state = 'enabled'
        driver.execute_script('flutter:waitFor', finder.byValueKey('enabled-button'), 3000);
    except TimeoutException as innerE:
        raise Exception('Button is not found')
```

After all that, you can compare the button_state data as desired

**Comment by KazuCocoa** [comment]
Created https://github.com/appium/appium-flutter-driver/issues/703 to define a command which does the `waitFor` behind that as part of this driver. Maybe it could be a workaround right now.
