### ISSUE TITLE
Can I test release build of app using appium flutter driver?

### ISSUE THREAD

**Issue by kritika333** [appium/appium-flutter-driver#709]
appium flutter driver only support testing in debug mode app , how reliable can this testing be , when the actual testing should be performed on release app.

Is there anyway I can test release mode app using appium flutter driver?

**Comment by KazuCocoa** [comment]
No, Flutter testing tools themselves do not work with a release build. At least they require additional dependencies etc.

UIA2/XCUITest is the only method to test release apps.
https://github.com/appium/appium-flutter-driver?tab=readme-ov-file#appium-flutter-driver-or-appium-uiautomator2xcuitest-driver
