### ISSUE TITLE
getWidgetDiagnostics method can't working ?

### ISSUE THREAD

**Issue by pornpawit08** [appium/appium-flutter-driver#710]
this my example (python)
![image](https://github.com/appium/appium-flutter-driver/assets/106052825/38e0e3eb-0fd4-4c21-b82b-eac044232f67)
getWidgetDiagnostics is not support ?
![image](https://github.com/appium/appium-flutter-driver/assets/106052825/77030aff-38fb-4b5d-8549-776a6e879f9a)

**Comment by KazuCocoa** [comment]
It is not released yet. I'll do it tonight.

**Comment by KazuCocoa** [comment]
v 2.8.0 should have the command.
