### ISSUE TITLE
Unable to Interact with Elements Beyond Splash Screen in Flutter App

### ISSUE THREAD

**Issue by Shivasiny** [appium/appium-flutter-driver#741]
I’m currently facing issues with automating my Flutter app using AppiumFlutterDriver with Java.  While the driver can interact with the splash screen element, I am unable to interact with any other elements in the app. The application is a dynamically changing newspaper app, which may be affecting element recognition.

Our app hasn’t provided accessibility keys for all elements. I have tried using Key, Semantics Label, and Text, but these methods only work for the splash screen element; they do not work for any other elements.

Any guidance or insights on how to resolve this issue would be greatly appreciated.

**Comment by balakumaran-deriv** [comment]
Maybe can try setting the setFrameSync to false
`driver.execute('flutter:setFrameSync', bool , durationMilliseconds)`

**Comment by Shivasiny** [comment]
Thank you.. It is working
