### ISSUE TITLE
appium inspector not work

### ISSUE THREAD

**Issue by fauzisunarya** [appium/appium-flutter-driver#744]
Hello, I am using the Appium inspector to get the selector on the flutter application. But I am experiencing the following problems. What is the solution? I have followed all the documentation in the Flutter Appium driver.

![image](https://github.com/user-attachments/assets/2002884a-c42a-4124-9064-b81bbbbc4694)

![image](https://github.com/user-attachments/assets/9086b89e-0f64-4175-88ff-e0dcddb31b3d)

**Comment by KazuCocoa** [comment]
It is expected because:

> Flutter context does not support page source
>    Please use getRenderTree command instead

https://github.com/appium/appium-flutter-driver?tab=readme-ov-file#note


Please use NATIVE_APP context. To get available element resources, please use `getRenderTree` command as addressed in the README

**Comment by fauzisunarya** [comment]
@KazuCocoa I have read it, but I am confused about getRenderTree, where to put it, please help me

**Comment by KazuCocoa** [comment]
It needs to call via execute_script. The response is text, so it does not work with the inspector.
https://github.com/appium/appium-flutter-driver?tab=readme-ov-file#commands
https://appium.io/docs/en/latest/guides/execute-methods/
