### ISSUE TITLE
Is the readme file correct about finding by key

### ISSUE THREAD

**Issue by herby-naidz** [appium/appium-flutter-driver#754]
Hi,

In the readme file for this driver under one of the bullets under the heading "Appium Flutter Driver or Appium UiAutomator2/XCUITest driver" it reads:

"Flutter 3.19 may have [identifier for SemanticsProperties](https://api.flutter.dev/flutter/semantics/SemanticsProperties/identifier.html) (introduced by https://github.com/flutter/flutter/pull/138331). It sets resource-id and accessibilityIdentifier for Android and iOS, then UiAutomator2/XCUITest drivers also can handle Key without this driver"

My question is about this part: _then UiAutomator2/XCUITest drivers also can handle **Key** without this driver_

Is this correct? What do I do to get UiAutomator2 to handle Key? I don't see anything about this in the UiAutomator2 docs.

Thanks

**Comment by KazuCocoa** [comment]
Have you set `identifier` in your flutter app like usually do via Key class in the past e.g. https://github.com/KazuCocoa/my_flutter_app3/commit/093c7096ac87295bbb27b520fefb098d30cc5302 ?

**Comment by KazuCocoa** [comment]
Afaik, Flutter does not expose the' Key' to the OS side, which is necessary for UIA2/XCUITest drivers to identify elements via the OS's accessibility feature.
https://dev.to/theotherdevs/mastering-flutter-semantics-24b like this article may help to check the Semantics' usage.

**Comment by herby-naidz** [comment]
Yes, this is my experience as well. So what does the readme mean when it says: _then UiAutomator2/XCUITest drivers also can handle Key without this driver_ ?

**Comment by herby-naidz** [comment]
Thanks for changing the wording. It makes more sense now.
